In [12]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

# pd.set_option('display.max_rows', None)
pd.set_option('display.max_rows', None)

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

In [13]:
description_df = pd.read_excel('LCDataDictionary.xlsx')

In [14]:
description_df.head()

,LoanStatNew,Description
0,acc_now_delinq,The number of accounts on which the borrower is now delinquent.
1,acc_open_past_24mths,Number of trades opened in past 24 months.
2,addr_state,The state provided by the borrower in the loan application
3,all_util,Balance to credit limit on all trades
4,annual_inc,The self-reported annual income provided by the borrower during registration.

In [15]:
description_df.to_csv('description')

In [16]:
description_df.to_dict()

{'LoanStatNew': {0: 'acc_now_delinq',
  1: 'acc_open_past_24mths',
  2: 'addr_state',
  3: 'all_util',
  4: 'annual_inc',
  5: 'annual_inc_joint',
  6: 'application_type',
  7: 'avg_cur_bal',
  8: 'bc_open_to_buy',
  9: 'bc_util',
  10: 'chargeoff_within_12_mths',
  11: 'collection_recovery_fee',
  12: 'collections_12_mths_ex_med',
  13: 'delinq_2yrs',
  14: 'delinq_amnt',
  15: 'desc',
  16: 'dti',
  17: 'dti_joint',
  18: 'earliest_cr_line',
  19: 'emp_length',
  20: 'emp_title',
  21: 'fico_range_high',
  22: 'fico_range_low',
  23: 'funded_amnt',
  24: 'funded_amnt_inv',
  25: 'grade',
  26: 'home_ownership',
  27: 'id',
  28: 'il_util',
  29: 'initial_list_status',
  30: 'inq_fi',
  31: 'inq_last_12m',
  32: 'inq_last_6mths',
  33: 'installment',
  34: 'int_rate',
  35: 'issue_d',
  36: 'last_credit_pull_d',
  37: 'last_fico_range_high',
  38: 'last_fico_range_low',
  39: 'last_pymnt_amnt',
  40: 'last_pymnt_d',
  41: 'loan_amnt',
  42: 'loan_status',
  43: 'max_bal_bc',
  44: 'member_id',
  45: 'mo_sin_old_il_acct',
  46: 'mo_sin_old_rev_tl_op',
  47: 'mo_sin_rcnt_rev_tl_op',
  48: 'mo_sin_rcnt_tl',
  49: 'mort_acc',
  50: 'mths_since_last_delinq',
  51: 'mths_since_last_major_derog',
  52: 'mths_since_last_record',
  53: 'mths_since_rcnt_il',
  54: 'mths_since_recent_bc',
  55: 'mths_since_recent_bc_dlq',
  56: 'mths_since_recent_inq',
  57: 'mths_since_recent_revol_delinq',
  58: 'next_pymnt_d',
  59: 'num_accts_ever_120_pd',
  60: 'num_actv_bc_tl',
  61: 'num_actv_rev_tl',
  62: 'num_bc_sats',
  63: 'num_bc_tl',
  64: 'num_il_tl',
  65: 'num_op_rev_tl',
  66: 'num_rev_accts',
  67: 'num_rev_tl_bal_gt_0',
  68: 'num_sats',
  69: 'num_tl_120dpd_2m',
  70: 'num_tl_30dpd',
  71: 'num_tl_90g_dpd_24m',
  72: 'num_tl_op_past_12m',
  73: 'open_acc',
  74: 'open_acc_6m',
  75: 'open_il_12m',
  76: 'open_il_24m',
  77: 'open_act_il',
  78: 'open_rv_12m',
  79: 'open_rv_24m',
  80: 'out_prncp',
  81: 'out_prncp_inv',
  82: 'pct_tl_nvr_dlq',
  83: 'percent_bc_gt_75',
  84: 'policy_code',
  85: 'pub_rec',
  86: 'pub_rec_bankruptcies',
  87: 'purpose',
  88: 'pymnt_plan',
  89: 'recoveries',
  90: 'revol_bal',
  91: 'revol_util',
  92: 'sub_grade',
  93: 'tax_liens',
  94: 'term',
  95: 'title',
  96: 'tot_coll_amt',
  97: 'tot_cur_bal',
  98: 'tot_hi_cred_lim',
  99: 'total_acc',
  100: 'total_bal_ex_mort',
  101: 'total_bal_il',
  102: 'total_bc_limit',
  103: 'total_cu_tl',
  104: 'total_il_high_credit_limit',
  105: 'total_pymnt',
  106: 'total_pymnt_inv',
  107: 'total_rec_int',
  108: 'total_rec_late_fee',
  109: 'total_rec_prncp',
  110: 'total_rev_hi_lim \xa0',
  111: 'url',
  112: 'verification_status',
  113: 'verified_status_joint',
  114: 'zip_code',
  115: 'revol_bal_joint ',
  116: 'sec_app_fico_range_low ',
  117: 'sec_app_fico_range_high ',
  118: 'sec_app_earliest_cr_line ',
  119: 'sec_app_inq_last_6mths ',
  120: 'sec_app_mort_acc ',
  121: 'sec_app_open_acc ',
  122: 'sec_app_revol_util ',
  123: 'sec_app_open_act_il',
  124: 'sec_app_num_rev_accts ',
  125: 'sec_app_chargeoff_within_12_mths ',
  126: 'sec_app_collections_12_mths_ex_med ',
  127: 'sec_app_mths_since_last_major_derog ',
  128: 'hardship_flag',
  129: 'hardship_type',
  130: 'hardship_reason',
  131: 'hardship_status',
  132: 'deferral_term',
  133: 'hardship_amount',
  134: 'hardship_start_date',
  135: 'hardship_end_date',
  136: 'payment_plan_start_date',
  137: 'hardship_length',
  138: 'hardship_dpd',
  139: 'hardship_loan_status',
  140: 'orig_projected_additional_accrued_interest',
  141: 'hardship_payoff_balance_amount',
  142: 'hardship_last_payment_amount',
  143: 'disbursement_method',
  144: 'debt_settlement_flag',
  145: 'debt_settlement_flag_date',
  146: 'settlement_status',
  147: 'settlement_date',
  148: 'settlement_amount',
  149: 'settlement_percentage',
  150: 'settlement_term',
  151: nan,
  152: nan},
 'Description': {0: 'The number of accounts on which the borrower is now delinquent.',
  1: 'Number of trades opened in past 24 months.',
  2: 'The state provided by the borrower in the loan application',
  3: 'Balance to credit limit on all trades',
  4: 'The self-reported annual income provided by the borrower during registration.',
  5: 'The combined self-reported annual income provided by the co-borrowers during registration',
  6: 'Indicates whether the loan is an individual application or a joint application with two co-borrowers',
  7: 'Average current balance of all accounts',
  8: 'Total open to buy on revolving bankcards.',
  9: 'Ratio of total current balance to high credit/credit limit for all bankcard accounts.',
  10: 'Number of charge-offs within 12 months',
  11: 'post charge off collection fee',
  12: 'Number of collections in 12 months excluding medical collections',
  13: "The number of 30+ days past-due incidences of delinquency in the borrower's credit file for the past 2 years",
  14: 'The past-due amount owed for the accounts on which the borrower is now delinquent.',
  15: 'Loan description provided by the borrower',
  16: 'A ratio calculated using the borrower’s total monthly debt payments on the total debt obligations, excluding mortgage and the requested LC loan, divided by the borrower’s self-reported monthly income.',
  17: "A ratio calculated using the co-borrowers' total monthly payments on the total debt obligations, excluding mortgages and the requested LC loan, divided by the co-borrowers' combined self-reported monthly income",
  18: "The month the borrower's earliest reported credit line was opened",
  19: 'Employment length in years. Possible values are between 0 and 10 where 0 means less than one year and 10 means ten or more years. ',
  20: 'The job title supplied by the Borrower when applying for the loan.*',
  21: 'The upper boundary range the borrower’s FICO at loan origination belongs to.',
  22: 'The lower boundary range the borrower’s FICO at loan origination belongs to.',
  23: 'The total amount committed to that loan at that point in time.',
  24: 'The total amount committed by investors for that loan at that point in time.',
  25: 'LC assigned loan grade',
  26: 'The home ownership status provided by the borrower during registration\xa0or obtained from the credit report.\xa0Our values are: RENT, OWN, MORTGAGE, OTHER',
  27: 'A unique LC assigned ID for the loan listing.',
  28: 'Ratio of total current balance to high credit/credit limit on all install acct',
  29: 'The initial listing status of the loan. Possible values are – W, F',
  30: 'Number of personal finance inquiries',
  31: 'Number of credit inquiries in past 12 months',
  32: 'The number of inquiries in past 6 months (excluding auto and mortgage inquiries)',
  33: 'The monthly payment owed by the borrower if the loan originates.',
  34: 'Interest Rate on the loan',
  35: 'The month which the loan was funded',
  36: 'The most recent month LC pulled credit for this loan',
  37: 'The upper boundary range the borrower’s last FICO pulled belongs to.',
  38: 'The lower boundary range the borrower’s last FICO pulled belongs to.',
  39: 'Last total payment amount received',
  40: 'Last month payment was received',
  41: 'The listed amount of the loan applied for by the borrower. If at some point in time, the credit department reduces the loan amount, then it will be reflected in this value.',
  42: 'Current status of the loan',
  43: 'Maximum current balance owed on all revolving accounts',
  44: 'A unique LC assigned Id for the borrower member.',
  45: 'Months since oldest bank installment account opened',
  46: 'Months since oldest revolving account opened',
  47: 'Months since most recent revolving account opened',
  48: 'Months since most recent account opened',
  49: 'Number of mortgage accounts.',
  50: "The number of months since the borrower's last delinquency.",
  51: 'Months since most recent 90-day or worse rating',
  52: 'The number of months since the last public record.',
  53: 'Months since most recent installment accounts opened',
  54: 'Months since most recent bankcard account opened.',
  55: 'Months since most recent bankcard delinquency',
  56: 'Months since most recent inquiry.',
  57: 'Months since most recent revolving delinquency.',
  58: 'Next scheduled payment date',
  59: 'Number of accounts ever 120 or more days past due',
  60: 'Number of currently active bankcard accounts',
  61: 'Number of currently active revolving trades',
  62: 'Number of satisfactory bankcard accounts',
  63: 'Number of bankcard accounts',
  64: 'Number of installment accounts',
  65: 'Number of open revolving accounts',
  66: 'Number of revolving accounts',
  67: 'Number of revolving trades with balance >0',
  68: 'Number of satisfactory accounts',
  69: 'Number of accounts currently 120 days past due (updated in past 2 months)',
  70: 'Number of accounts currently 30 days past due (updated in past 2 months)',
  71: 'Number of accounts 90 or more days past due in last 24 months',
  72: 'Number of accounts opened in past 12 months',
  73: "The number of open credit lines in the borrower's credit file.",
  74: 'Number of open trades in last 6 months',
  75: 'Number of installment accounts opened in past 12 months',
  76: 'Number of installment accounts opened in past 24 months',
  77: 'Number of currently active installment trades',
  78: 'Number of revolving trades opened in past 12 months',
  79: 'Number of revolving trades opened in past 24 months',
  80: 'Remaining outstanding principal for total amount funded',
  81: 'Remaining outstanding principal for portion of total amount funded by investors',
  82: 'Percent of trades never delinquent',
  83: 'Percentage of all bankcard accounts > 75% of limit.',
  84: 'publicly available policy_code=1\nnew products not publicly available policy_code=2',
  85: 'Number of derogatory public records',
  86: 'Number of public record bankruptcies',
  87: 'A category provided by the borrower for the loan request. ',
  88: 'Indicates if a payment plan has been put in place for the loan',
  89: 'post charge off gross recovery',
  90: 'Total credit revolving balance',
  91: 'Revolving line utilization rate, or the amount of credit the borrower is using relative to all available revolving credit.',
  92: 'LC assigned loan subgrade',
  93: 'Number of tax liens',
  94: 'The number of payments on the loan. Values are in months and can be either 36 or 60.',
  95: 'The loan title provided by the borrower',
  96: 'Total collection amounts ever owed',
  97: 'Total current balance of all accounts',
  98: 'Total high credit/credit limit',
  99: "The total number of credit lines currently in the borrower's credit file",
  100: 'Total credit balance excluding mortgage',
  101: 'Total current balance of all installment accounts',
  102: 'Total bankcard high credit/credit limit',
  103: 'Number of finance trades',
  104: 'Total installment high credit/credit limit',
  105: 'Payments received to date for total amount funded',
  106: 'Payments received to date for portion of total amount funded by investors',
  107: 'Interest received to date',
  108: 'Late fees received to date',
  109: 'Principal received to date',
  110: 'Total revolving high credit/credit limit',
  111: 'URL for the LC page with listing data.',
  112: 'Indicates if income was verified by LC, not verified, or if the income source was verified',
  113: "Indicates if the co-borrowers' joint income was verified by LC, not verified, or if the income source was verified",
  114: 'The first 3 numbers of the zip code provided by the borrower in the loan application.',
  115: ' Sum of revolving credit balance of the co-borrowers, net of duplicate balances',
  116: ' FICO range (high) for the secondary applicant',
  117: ' FICO range (low) for the secondary applicant',
  118: ' Earliest credit line at time of application for the secondary applicant',
  119: ' Credit inquiries in the last 6 months at time of application for the secondary applicant',
  120: ' Number of mortgage accounts at time of application for the secondary applicant',
  121: ' Number of open trades at time of application for the secondary applicant',
  122: ' Ratio of total current balance to high credit/credit limit for all revolving accounts',
  123: ' Number of currently active installment trades at time of application for the secondary applicant',
  124: ' Number of revolving accounts at time of application for the secondary applicant',
  125: ' Number of charge-offs within last 12 months at time of application for the secondary applicant',
  126: ' Number of collections within last 12 months excluding medical collections at time of application for the secondary applicant',
  127: ' Months since most recent 90-day or worse rating at time of application for the secondary applicant',
  128: 'Flags whether or not the borrower is on a hardship plan',
  129: 'Describes the hardship plan offering',
  130: 'Describes the reason the hardship plan was offered',
  131: 'Describes if the hardship plan is active, pending, canceled, completed, or broken',
  132: 'Amount of months that the borrower is expected to pay less than the contractual monthly payment amount due to a hardship plan',
  133: 'The interest payment that the borrower has committed to make each month while they are on a hardship plan',
  134: 'The start date of the hardship plan period',
  135: 'The end date of the hardship plan period',
  136: 'The day the first hardship plan payment is due. For example, if a borrower has a hardship plan period of 3 months, the start date is the start of the three-month period in which the borrower is allowed to make interest-only payments.',
  137: 'The number of months the borrower will make smaller payments than normally obligated due to a hardship plan',
  138: 'Account days past due as of the hardship plan start date',
  139: 'Loan Status as of the hardship plan start date',
  140: 'The original projected additional interest amount that will accrue for the given hardship payment plan as of the Hardship Start Date. This field will be null if the borrower has broken their hardship payment plan.',
  141: 'The payoff balance amount as of the hardship plan start date',
  142: 'The last payment amount as of the hardship plan start date',
  143: 'The method by which the borrower receives their loan. Possible values are: CASH, DIRECT_PAY',
  144: 'Flags whether or not the borrower, who has charged-off, is working with a debt-settlement company.',
  145: 'The most recent date that the Debt_Settlement_Flag has been set\xa0\xa0',
  146: 'The status of the borrower’s settlement plan. Possible values are: COMPLETE, ACTIVE, BROKEN, CANCELLED, DENIED, DRAFT',
  147: 'The date that the borrower agrees to the settlement plan',
  148: 'The loan amount that the borrower has agreed to settle for',
  149: 'The settlement amount as a percentage of the payoff balance amount on the loan',
  150: 'The number of months that the borrower will be on the settlement plan',
  151: nan,
  152: '* Employer Title replaces Employer Name for all loans listed after 9/23/2013'}}

In [17]:
description_df.to_dict().get('Description')

{0: 'The number of accounts on which the borrower is now delinquent.',
 1: 'Number of trades opened in past 24 months.',
 2: 'The state provided by the borrower in the loan application',
 3: 'Balance to credit limit on all trades',
 4: 'The self-reported annual income provided by the borrower during registration.',
 5: 'The combined self-reported annual income provided by the co-borrowers during registration',
 6: 'Indicates whether the loan is an individual application or a joint application with two co-borrowers',
 7: 'Average current balance of all accounts',
 8: 'Total open to buy on revolving bankcards.',
 9: 'Ratio of total current balance to high credit/credit limit for all bankcard accounts.',
 10: 'Number of charge-offs within 12 months',
 11: 'post charge off collection fee',
 12: 'Number of collections in 12 months excluding medical collections',
 13: "The number of 30+ days past-due incidences of delinquency in the borrower's credit file for the past 2 years",
 14: 'The past-due amount owed for the accounts on which the borrower is now delinquent.',
 15: 'Loan description provided by the borrower',
 16: 'A ratio calculated using the borrower’s total monthly debt payments on the total debt obligations, excluding mortgage and the requested LC loan, divided by the borrower’s self-reported monthly income.',
 17: "A ratio calculated using the co-borrowers' total monthly payments on the total debt obligations, excluding mortgages and the requested LC loan, divided by the co-borrowers' combined self-reported monthly income",
 18: "The month the borrower's earliest reported credit line was opened",
 19: 'Employment length in years. Possible values are between 0 and 10 where 0 means less than one year and 10 means ten or more years. ',
 20: 'The job title supplied by the Borrower when applying for the loan.*',
 21: 'The upper boundary range the borrower’s FICO at loan origination belongs to.',
 22: 'The lower boundary range the borrower’s FICO at loan origination belongs to.',
 23: 'The total amount committed to that loan at that point in time.',
 24: 'The total amount committed by investors for that loan at that point in time.',
 25: 'LC assigned loan grade',
 26: 'The home ownership status provided by the borrower during registration\xa0or obtained from the credit report.\xa0Our values are: RENT, OWN, MORTGAGE, OTHER',
 27: 'A unique LC assigned ID for the loan listing.',
 28: 'Ratio of total current balance to high credit/credit limit on all install acct',
 29: 'The initial listing status of the loan. Possible values are – W, F',
 30: 'Number of personal finance inquiries',
 31: 'Number of credit inquiries in past 12 months',
 32: 'The number of inquiries in past 6 months (excluding auto and mortgage inquiries)',
 33: 'The monthly payment owed by the borrower if the loan originates.',
 34: 'Interest Rate on the loan',
 35: 'The month which the loan was funded',
 36: 'The most recent month LC pulled credit for this loan',
 37: 'The upper boundary range the borrower’s last FICO pulled belongs to.',
 38: 'The lower boundary range the borrower’s last FICO pulled belongs to.',
 39: 'Last total payment amount received',
 40: 'Last month payment was received',
 41: 'The listed amount of the loan applied for by the borrower. If at some point in time, the credit department reduces the loan amount, then it will be reflected in this value.',
 42: 'Current status of the loan',
 43: 'Maximum current balance owed on all revolving accounts',
 44: 'A unique LC assigned Id for the borrower member.',
 45: 'Months since oldest bank installment account opened',
 46: 'Months since oldest revolving account opened',
 47: 'Months since most recent revolving account opened',
 48: 'Months since most recent account opened',
 49: 'Number of mortgage accounts.',
 50: "The number of months since the borrower's last delinquency.",
 51: 'Months since most recent 90-day or worse rating',
 52: 'The number of months since the last public record.',
 53: 'Months since most recent installment accounts opened',
 54: 'Months since most recent bankcard account opened.',
 55: 'Months since most recent bankcard delinquency',
 56: 'Months since most recent inquiry.',
 57: 'Months since most recent revolving delinquency.',
 58: 'Next scheduled payment date',
 59: 'Number of accounts ever 120 or more days past due',
 60: 'Number of currently active bankcard accounts',
 61: 'Number of currently active revolving trades',
 62: 'Number of satisfactory bankcard accounts',
 63: 'Number of bankcard accounts',
 64: 'Number of installment accounts',
 65: 'Number of open revolving accounts',
 66: 'Number of revolving accounts',
 67: 'Number of revolving trades with balance >0',
 68: 'Number of satisfactory accounts',
 69: 'Number of accounts currently 120 days past due (updated in past 2 months)',
 70: 'Number of accounts currently 30 days past due (updated in past 2 months)',
 71: 'Number of accounts 90 or more days past due in last 24 months',
 72: 'Number of accounts opened in past 12 months',
 73: "The number of open credit lines in the borrower's credit file.",
 74: 'Number of open trades in last 6 months',
 75: 'Number of installment accounts opened in past 12 months',
 76: 'Number of installment accounts opened in past 24 months',
 77: 'Number of currently active installment trades',
 78: 'Number of revolving trades opened in past 12 months',
 79: 'Number of revolving trades opened in past 24 months',
 80: 'Remaining outstanding principal for total amount funded',
 81: 'Remaining outstanding principal for portion of total amount funded by investors',
 82: 'Percent of trades never delinquent',
 83: 'Percentage of all bankcard accounts > 75% of limit.',
 84: 'publicly available policy_code=1\nnew products not publicly available policy_code=2',
 85: 'Number of derogatory public records',
 86: 'Number of public record bankruptcies',
 87: 'A category provided by the borrower for the loan request. ',
 88: 'Indicates if a payment plan has been put in place for the loan',
 89: 'post charge off gross recovery',
 90: 'Total credit revolving balance',
 91: 'Revolving line utilization rate, or the amount of credit the borrower is using relative to all available revolving credit.',
 92: 'LC assigned loan subgrade',
 93: 'Number of tax liens',
 94: 'The number of payments on the loan. Values are in months and can be either 36 or 60.',
 95: 'The loan title provided by the borrower',
 96: 'Total collection amounts ever owed',
 97: 'Total current balance of all accounts',
 98: 'Total high credit/credit limit',
 99: "The total number of credit lines currently in the borrower's credit file",
 100: 'Total credit balance excluding mortgage',
 101: 'Total current balance of all installment accounts',
 102: 'Total bankcard high credit/credit limit',
 103: 'Number of finance trades',
 104: 'Total installment high credit/credit limit',
 105: 'Payments received to date for total amount funded',
 106: 'Payments received to date for portion of total amount funded by investors',
 107: 'Interest received to date',
 108: 'Late fees received to date',
 109: 'Principal received to date',
 110: 'Total revolving high credit/credit limit',
 111: 'URL for the LC page with listing data.',
 112: 'Indicates if income was verified by LC, not verified, or if the income source was verified',
 113: "Indicates if the co-borrowers' joint income was verified by LC, not verified, or if the income source was verified",
 114: 'The first 3 numbers of the zip code provided by the borrower in the loan application.',
 115: ' Sum of revolving credit balance of the co-borrowers, net of duplicate balances',
 116: ' FICO range (high) for the secondary applicant',
 117: ' FICO range (low) for the secondary applicant',
 118: ' Earliest credit line at time of application for the secondary applicant',
 119: ' Credit inquiries in the last 6 months at time of application for the secondary applicant',
 120: ' Number of mortgage accounts at time of application for the secondary applicant',
 121: ' Number of open trades at time of application for the secondary applicant',
 122: ' Ratio of total current balance to high credit/credit limit for all revolving accounts',
 123: ' Number of currently active installment trades at time of application for the secondary applicant',
 124: ' Number of revolving accounts at time of application for the secondary applicant',
 125: ' Number of charge-offs within last 12 months at time of application for the secondary applicant',
 126: ' Number of collections within last 12 months excluding medical collections at time of application for the secondary applicant',
 127: ' Months since most recent 90-day or worse rating at time of application for the secondary applicant',
 128: 'Flags whether or not the borrower is on a hardship plan',
 129: 'Describes the hardship plan offering',
 130: 'Describes the reason the hardship plan was offered',
 131: 'Describes if the hardship plan is active, pending, canceled, completed, or broken',
 132: 'Amount of months that the borrower is expected to pay less than the contractual monthly payment amount due to a hardship plan',
 133: 'The interest payment that the borrower has committed to make each month while they are on a hardship plan',
 134: 'The start date of the hardship plan period',
 135: 'The end date of the hardship plan period',
 136: 'The day the first hardship plan payment is due. For example, if a borrower has a hardship plan period of 3 months, the start date is the start of the three-month period in which the borrower is allowed to make interest-only payments.',
 137: 'The number of months the borrower will make smaller payments than normally obligated due to a hardship plan',
 138: 'Account days past due as of the hardship plan start date',
 139: 'Loan Status as of the hardship plan start date',
 140: 'The original projected additional interest amount that will accrue for the given hardship payment plan as of the Hardship Start Date. This field will be null if the borrower has broken their hardship payment plan.',
 141: 'The payoff balance amount as of the hardship plan start date',
 142: 'The last payment amount as of the hardship plan start date',
 143: 'The method by which the borrower receives their loan. Possible values are: CASH, DIRECT_PAY',
 144: 'Flags whether or not the borrower, who has charged-off, is working with a debt-settlement company.',
 145: 'The most recent date that the Debt_Settlement_Flag has been set\xa0\xa0',
 146: 'The status of the borrower’s settlement plan. Possible values are: COMPLETE, ACTIVE, BROKEN, CANCELLED, DENIED, DRAFT',
 147: 'The date that the borrower agrees to the settlement plan',
 148: 'The loan amount that the borrower has agreed to settle for',
 149: 'The settlement amount as a percentage of the payoff balance amount on the loan',
 150: 'The number of months that the borrower will be on the settlement plan',
 151: nan,
 152: '* Employer Title replaces Employer Name for all loans listed after 9/23/2013'}

In [18]:
# Reading the raw data provided by Lending Club
df = pd.read_csv("loan.csv")

In [19]:
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,Chef,10+ years,RENT,55000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,109xx,NY,18.24,0.0,Apr-2001,1.0,NaN,45.0,9.0,1.0,4341,10.3,34.0,w,2386.02,2386.02,167.02,167.02,113.98,53.04,0.0,0.0,0.0,Feb-2019,84.92,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,16901.0,2.0,2.0,1.0,2.0,2.0,12560.0,69.0,2.0,7.0,2137.0,28.0,42000.0,1.0,11.0,2.0,9.0,1878.0,34360.0,5.9,0.0,0.0,140.0,212.0,1.0,1.0,0.0,1.0,NaN,2.0,NaN,0.0,2.0,5.0,3.0,3.0,16.0,7.0,18.0,5.0,9.0,0.0,0.0,0.0,3.0,100.0,0.0,1.0,0.0,60124.0,16901.0,36500.0,18124.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,Postmaster,10+ years,MORTGAGE,90000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,713xx,LA,26.52,0.0,Jun-1987,0.0,71.0,75.0,13.0,1.0,12315,24.2,44.0,w,29387.75,29387.75,1507.11,1507.11,612.25,894.86,0.0,0.0,0.0,Feb-2019,777.23,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,1208.0,321915.0,4.0,4.0,2.0,3.0,3.0,87153.0,88.0,4.0,5.0,998.0,57.0,50800.0,2.0,15.0,2.0,10.0,24763.0,13761.0,8.3,0.0,0.0,163.0,378.0,4.0,3.0,3.0,4.0,NaN,4.0,NaN,0.0,2.0,4.0,4.0,9.0,27.0,8.0,14.0,4.0,13.0,0.0,0.0,0.0,6.0,95.0,0.0,1.0,0.0,372872.0,99468.0,15000.0,94072.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,490xx,MI,10.51,0.0,Apr-2011,0.0,NaN,NaN,8.0,0.0,4599,19.1,13.0,w,4787.21,4787.21,353.89,353.89,212.79,141.10,0.0,0.0,0.0,Feb-2019,180.69,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,110299.0,0.0,1.0,0.0,2.0,14.0,7150.0,72.0,0.0,2.0,0.0,35.0,24100.0,1.0,5.0,0.0,4.0,18383.0,13800.0,0.0,0.0,0.0,87.0,92.0,15.0,14.0,2.0,77.0,NaN,14.0,NaN,0.0,0.0,3.0,3.0,3.0,4.0,6.0,7.0,3.0,8.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,136927.0,11749.0,13800.0,10000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,IT Supervisor,10+ years,MORTGAGE,92000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,985xx,WA,16.74,0.0,Feb-2006,0.0,NaN,NaN,10.0,0.0,5468,78.1,13.0,w,3831.93,3831.93,286.71,286.71,168.07,118.64,0.0,0.0,0.0,Feb-2019,146.51,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,686.0,305049.0,1.0,5.0,3.0,5.0,5.0,30683.0,68.0,0.0,0.0,3761.0,70.0,7000.0,2.0,4.0,3.0,5.0,30505.0,1239.0,75.2,0.0,0.0,62.0,154.0,64.0,5.0,3.0,64.0,NaN,5.0,NaN,0.0,1.0,2.0,1.0,2.0,7.0,2.0,3.0,2.0,10.0,0.0,0.0,0.0,3.0,100.0,100.0,0.0,0.0,385183.0,36151.0,5000.0,44984.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,Mechanic,10+ years,MORTGAGE,57250.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,212xx,MD,26.35,0.0,Dec-2000,0.0,NaN,NaN,12.0,0.0,829,3.6,26.0,w,29339.02,29339.02,1423.21,1423.21,660.98,762.23,0.0,0.0,0.0,Feb-2019,731.78,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,116007.0,3.0,5.0,3.0,5.0,4.0,28845.0,89.0,2.0,4.0,516.0,54.0,23100.0,1.0,0.0,0.0,9.0,9667.0,8471.0,8.9,0.0,0.0,53.0,216.0,2.0,2.0,2.0,2.0,NaN,13.0,NaN,0.0,2.0,2.0,3.0,8.0,9.0,6.0,15.0,2.0,12.0,0.0,0.0,0.0,5.0,92.3,0.0,0.0,0.0,157548.0,29674.0,9300.0,32332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
loan = loan[(df.loan_status== 'Charged Off')|(df.loan_status== 'Fully Paid')]

In [ ]:
loan.shape

In [17]:
loan.info()

(1303607, 145)

In [20]:
# Overview of all the predictors provided by the Lending Club
# Unfortunately many of these are NaN particularly those indicators that might help us
# with an analysis of any potential discrimination.
# Descriptions related to these terms are provided in a separate Excel file

for column in loan.columns:
    print("%-40s"%column, loan[column].dtype)
    print(column)

id                                       float64
id
member_id                                float64
member_id
loan_amnt                                int64
loan_amnt
funded_amnt                              int64
funded_amnt
funded_amnt_inv                          float64
funded_amnt_inv
term                                     object
term
int_rate                                 float64
int_rate
installment                              float64
installment
grade                                    object
grade
sub_grade                                object
sub_grade
emp_title                                object
emp_title
emp_length                               object
emp_length
home_ownership                           object
home_ownership
annual_inc                               float64
annual_inc
verification_status                      object
verification_status
issue_d                                  object
issue_d
loan_status                              object
loan_status
pymnt_plan                               object
pymnt_plan
url                                      float64
url
desc                                     object
desc
purpose                                  object
purpose
title                                    object
title
zip_code                                 object
zip_code
addr_state                               object
addr_state
dti                                      float64
dti
delinq_2yrs                              float64
delinq_2yrs
earliest_cr_line                         object
earliest_cr_line
inq_last_6mths                           float64
inq_last_6mths
mths_since_last_delinq                   float64
mths_since_last_delinq
mths_since_last_record                   float64
mths_since_last_record
open_acc                                 float64
open_acc
pub_rec                                  float64
pub_rec
revol_bal                                int64
revol_bal
revol_util                               float64
revol_util
total_acc                                float64
total_acc
initial_list_status                      object
initial_list_status
out_prncp                                float64
out_prncp
out_prncp_inv                            float64
out_prncp_inv
total_pymnt                              float64
total_pymnt
total_pymnt_inv                          float64
total_pymnt_inv
total_rec_prncp                          float64
total_rec_prncp
total_rec_int                            float64
total_rec_int
total_rec_late_fee                       float64
total_rec_late_fee
recoveries                               float64
recoveries
collection_recovery_fee                  float64
collection_recovery_fee
last_pymnt_d                             object
last_pymnt_d
last_pymnt_amnt                          float64
last_pymnt_amnt
next_pymnt_d                             object
next_pymnt_d
last_credit_pull_d                       object
last_credit_pull_d
collections_12_mths_ex_med               float64
collections_12_mths_ex_med
mths_since_last_major_derog              float64
mths_since_last_major_derog
policy_code                              int64
policy_code
application_type                         object
application_type
annual_inc_joint                         float64
annual_inc_joint
dti_joint                                float64
dti_joint
verification_status_joint                object
verification_status_joint
acc_now_delinq                           float64
acc_now_delinq
tot_coll_amt                             float64
tot_coll_amt
tot_cur_bal                              float64
tot_cur_bal
open_acc_6m                              float64
open_acc_6m
open_act_il                              float64
open_act_il
open_il_12m                              float64
open_il_12m
open_il_24m                              float64
open_il_24m
mths_since_rcnt_il                       float64
mths_since_rcnt_il
total_bal_il                             float64
total_bal_il
il_util                                  float64
il_util
open_rv_12m                              float64
open_rv_12m
open_rv_24m                              float64
open_rv_24m
max_bal_bc                               float64
max_bal_bc
all_util                                 float64
all_util
total_rev_hi_lim                         float64
total_rev_hi_lim
inq_fi                                   float64
inq_fi
total_cu_tl                              float64
total_cu_tl
inq_last_12m                             float64
inq_last_12m
acc_open_past_24mths                     float64
acc_open_past_24mths
avg_cur_bal                              float64
avg_cur_bal
bc_open_to_buy                           float64
bc_open_to_buy
bc_util                                  float64
bc_util
chargeoff_within_12_mths                 float64
chargeoff_within_12_mths
delinq_amnt                              float64
delinq_amnt
mo_sin_old_il_acct                       float64
mo_sin_old_il_acct
mo_sin_old_rev_tl_op                     float64
mo_sin_old_rev_tl_op
mo_sin_rcnt_rev_tl_op                    float64
mo_sin_rcnt_rev_tl_op
mo_sin_rcnt_tl                           float64
mo_sin_rcnt_tl
mort_acc                                 float64
mort_acc
mths_since_recent_bc                     float64
mths_since_recent_bc
mths_since_recent_bc_dlq                 float64
mths_since_recent_bc_dlq
mths_since_recent_inq                    float64
mths_since_recent_inq
mths_since_recent_revol_delinq           float64
mths_since_recent_revol_delinq
num_accts_ever_120_pd                    float64
num_accts_ever_120_pd
num_actv_bc_tl                           float64
num_actv_bc_tl
num_actv_rev_tl                          float64
num_actv_rev_tl
num_bc_sats                              float64
num_bc_sats
num_bc_tl                                float64
num_bc_tl
num_il_tl                                float64
num_il_tl
num_op_rev_tl                            float64
num_op_rev_tl
num_rev_accts                            float64
num_rev_accts
num_rev_tl_bal_gt_0                      float64
num_rev_tl_bal_gt_0
num_sats                                 float64
num_sats
num_tl_120dpd_2m                         float64
num_tl_120dpd_2m
num_tl_30dpd                             float64
num_tl_30dpd
num_tl_90g_dpd_24m                       float64
num_tl_90g_dpd_24m
num_tl_op_past_12m                       float64
num_tl_op_past_12m
pct_tl_nvr_dlq                           float64
pct_tl_nvr_dlq
percent_bc_gt_75                         float64
percent_bc_gt_75
pub_rec_bankruptcies                     float64
pub_rec_bankruptcies
tax_liens                                float64
tax_liens
tot_hi_cred_lim                          float64
tot_hi_cred_lim
total_bal_ex_mort                        float64
total_bal_ex_mort
total_bc_limit                           float64
total_bc_limit
total_il_high_credit_limit               float64
total_il_high_credit_limit
revol_bal_joint                          float64
revol_bal_joint
sec_app_earliest_cr_line                 object
sec_app_earliest_cr_line
sec_app_inq_last_6mths                   float64
sec_app_inq_last_6mths
sec_app_mort_acc                         float64
sec_app_mort_acc
sec_app_open_acc                         float64
sec_app_open_acc
sec_app_revol_util                       float64
sec_app_revol_util
sec_app_open_act_il                      float64
sec_app_open_act_il
sec_app_num_rev_accts                    float64
sec_app_num_rev_accts
sec_app_chargeoff_within_12_mths         float64
sec_app_chargeoff_within_12_mths
sec_app_collections_12_mths_ex_med       float64
sec_app_collections_12_mths_ex_med
sec_app_mths_since_last_major_derog      float64
sec_app_mths_since_last_major_derog
hardship_flag                            object
hardship_flag
hardship_type                            object
hardship_type
hardship_reason                          object
hardship_reason
hardship_status                          object
hardship_status
deferral_term                            float64
deferral_term
hardship_amount                          float64
hardship_amount
hardship_start_date                      object
hardship_start_date
hardship_end_date                        object
hardship_end_date
payment_plan_start_date                  object
payment_plan_start_date
hardship_length                          float64
hardship_length
hardship_dpd                             float64
hardship_dpd
hardship_loan_status                     object
hardship_loan_status
orig_projected_additional_accrued_interest float64
orig_projected_additional_accrued_interest
hardship_payoff_balance_amount           float64
hardship_payoff_balance_amount
hardship_last_payment_amount             float64
hardship_last_payment_amount
disbursement_method                      object
disbursement_method
debt_settlement_flag                     object
debt_settlement_flag
debt_settlement_flag_date                object
debt_settlement_flag_date
settlement_status                        object
settlement_status
settlement_date                          object
settlement_date
settlement_amount                        float64
settlement_amount
settlement_percentage                    float64
settlement_percentage
settlement_term                          float64
settlement_term

In [8]:
loan.loan_status.value_counts()

loan_status
Fully Paid                                             1041952
Current                                                 919695
Charged Off                                             261655
Late (31-120 days)                                       21897
In Grace Period                                           8952
Late (16-30 days)                                         3737
Does not meet the credit policy. Status:Fully Paid        1988
Does not meet the credit policy. Status:Charged Off        761
Default                                                     31
Name: count, dtype: int64

In [21]:
loan.isna().sum()

id                                            2260668
member_id                                     2260668
loan_amnt                                           0
funded_amnt                                         0
funded_amnt_inv                                     0
term                                                0
int_rate                                            0
installment                                         0
grade                                               0
sub_grade                                           0
emp_title                                      166969
emp_length                                     146907
home_ownership                                      0
annual_inc                                          4
verification_status                                 0
issue_d                                             0
loan_status                                         0
pymnt_plan                                          0
url                                           2260668
desc                                          2134603
purpose                                             0
title                                           23326
zip_code                                            1
addr_state                                          0
dti                                              1711
delinq_2yrs                                        29
earliest_cr_line                                   29
inq_last_6mths                                     30
mths_since_last_delinq                        1158502
mths_since_last_record                        1901512
open_acc                                           29
pub_rec                                            29
revol_bal                                           0
revol_util                                       1802
total_acc                                          29
initial_list_status                                 0
out_prncp                                           0
out_prncp_inv                                       0
total_pymnt                                         0
total_pymnt_inv                                     0
total_rec_prncp                                     0
total_rec_int                                       0
total_rec_late_fee                                  0
recoveries                                          0
collection_recovery_fee                             0
last_pymnt_d                                     2426
last_pymnt_amnt                                     0
next_pymnt_d                                  1303607
last_credit_pull_d                                 73
collections_12_mths_ex_med                        145
mths_since_last_major_derog                   1679893
policy_code                                         0
application_type                                    0
annual_inc_joint                              2139958
dti_joint                                     2139962
verification_status_joint                     2144938
acc_now_delinq                                     29
tot_coll_amt                                    70276
tot_cur_bal                                     70276
open_acc_6m                                    866130
open_act_il                                    866129
open_il_12m                                    866129
open_il_24m                                    866129
mths_since_rcnt_il                             909924
total_bal_il                                   866129
il_util                                       1068850
open_rv_12m                                    866129
open_rv_24m                                    866129
max_bal_bc                                     866129
all_util                                       866348
total_rev_hi_lim                                70276
inq_fi                                         866129
total_cu_tl                                    866130
inq_last_12m                                   866130
acc_open_past_24mths                            50030
avg_cur_bal                                     70346
bc_open_to_buy                                  74935
bc_util                                         76071
chargeoff_within_12_mths                          145
delinq_amnt                                        29
mo_sin_old_il_acct                             139071
mo_sin_old_rev_tl_op                            70277
mo_sin_rcnt_rev_tl_op                           70277
mo_sin_rcnt_tl                                  70276
mort_acc                                        50030
mths_since_recent_bc                            73412
mths_since_recent_bc_dlq                      1740967
mths_since_recent_inq                          295435
mths_since_recent_revol_delinq                1520309
num_accts_ever_120_pd                           70276
num_actv_bc_tl                                  70276
num_actv_rev_tl                                 70276
num_bc_sats                                     58590
num_bc_tl                                       70276
num_il_tl                                       70276
num_op_rev_tl                                   70276
num_rev_accts                                   70277
num_rev_tl_bal_gt_0                             70276
num_sats                                        58590
num_tl_120dpd_2m                               153657
num_tl_30dpd                                    70276
num_tl_90g_dpd_24m                              70276
num_tl_op_past_12m                              70276
pct_tl_nvr_dlq                                  70431
percent_bc_gt_75                                75379
pub_rec_bankruptcies                             1365
tax_liens                                         105
tot_hi_cred_lim                                 70276
total_bal_ex_mort                               50030
total_bc_limit                                  50030
total_il_high_credit_limit                      70276
revol_bal_joint                               2152648
sec_app_earliest_cr_line                      2152647
sec_app_inq_last_6mths                        2152647
sec_app_mort_acc                              2152647
sec_app_open_acc                              2152647
sec_app_revol_util                            2154484
sec_app_open_act_il                           2152647
sec_app_num_rev_accts                         2152647
sec_app_chargeoff_within_12_mths              2152647
sec_app_collections_12_mths_ex_med            2152647
sec_app_mths_since_last_major_derog           2224726
hardship_flag                                       0
hardship_type                                 2250055
hardship_reason                               2250055
hardship_status                               2250055
deferral_term                                 2250055
hardship_amount                               2250055
hardship_start_date                           2250055
hardship_end_date                             2250055
payment_plan_start_date                       2250055
hardship_length                               2250055
hardship_dpd                                  2250055
hardship_loan_status                          2250055
orig_projected_additional_accrued_interest    2252242
hardship_payoff_balance_amount                2250055
hardship_last_payment_amount                  2250055
disbursement_method                                 0
debt_settlement_flag                                0
debt_settlement_flag_date                     2227612
settlement_status                             2227612
settlement_date                               2227612
settlement_amount                             2227612
settlement_percentage                         2227612
settlement_term                               2227612
dtype: int64

In [22]:
import re

def subgrade_score(s):
    return (ord(s[0]) - ord('A')) + (int(s[1]) - 1)/5

def extract_number(x): 
    try:
        return int(re.search(r"\d+", str(x)).group(0))
    except AttributeError:
        return np.nan

In [23]:
loan["zip_code_prefix"] = [extract_number(s) for s in loan.zip_code.astype(str)]

In [13]:
loan.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'hardship_last_payment_amount', 'disbursement_method',
       'debt_settlement_flag', 'debt_settlement_flag_date',
       'settlement_status', 'settlement_date', 'settlement_amount',
       'settlement_percentage', 'settlement_term', 'zip_code_prefix'],
      dtype='object', length=146)

In [14]:
# Record today's date in order to calculate loan length
now = pd.to_datetime("Aug-2018")
loan["earliest_cr_line_date"] = pd.to_datetime(loan.earliest_cr_line, 
                                               format="%b-%Y")
loan.earliest_cr_line_date.head()

0   2001-04-01
1   1987-06-01
2   2011-04-01
3   2006-02-01
4   2000-12-01
Name: earliest_cr_line_date, dtype: datetime64[ns]

In [15]:
# Overall credit history is then today's date less the date of the 
# First available information on the person's Credit history
loan["credit_history"] = now - loan.earliest_cr_line_date

In [16]:
loan["credit_history_years"] = loan.credit_history.dt.days.fillna(0) / 365.25

In [17]:
# Check that there are no 'NAs' in the credit history data column
loan.credit_history_years.isna().sum()

0

In [18]:
# Clean the length of employment predictor/column and check for 'NAs'
loan["emp_length_years"] = loan.emp_length.apply(extract_number)
loan["emp_length_years"].isna().sum()

146907

In [19]:
# Cleanse the data related to the loan inquiries made within the last 6 months
# This is a typical credit worthiness metric
# The more frequently somehow has asked for a loan the less credit-worthy they are
loan.inq_last_6mths = loan.inq_last_6mths.fillna(0)

In [20]:
# Clean up the column/predictor to the months since last delinquent payment
# This is part of the credit history of the borrower
loan.mths_since_last_delinq = loan.mths_since_last_delinq.fillna(0)
loan.mths_since_last_record = loan.mths_since_last_record.fillna(0)

In [21]:
# Clean the data related to the employment history of the borrower
m = np.mean(loan.emp_length_years)
loan.emp_length_years = loan.emp_length_years.fillna(m)
loan.emp_length_years.isna().sum()

0

In [22]:
# Impute the missing data for the annual income of the borrowed using the average
loan.annual_inc = loan.annual_inc.fillna(np.mean(loan.annual_inc))

In [23]:
loan.dti = loan.dti.fillna(np.mean(loan.dti))

In [24]:
for g in sorted(loan.sub_grade.unique()):
    print(g, subgrade_score(g))

A1 0.0
A2 0.2
A3 0.4
A4 0.6
A5 0.8
B1 1.0
B2 1.2
B3 1.4
B4 1.6
B5 1.8
C1 2.0
C2 2.2
C3 2.4
C4 2.6
C5 2.8
D1 3.0
D2 3.2
D3 3.4
D4 3.6
D5 3.8
E1 4.0
E2 4.2
E3 4.4
E4 4.6
E5 4.8
F1 5.0
F2 5.2
F3 5.4
F4 5.6
F5 5.8
G1 6.0
G2 6.2
G3 6.4
G4 6.6
G5 6.8

In [25]:
loan.int_rate.unique()

array([13.56, 18.94, 17.97, 16.14, 15.02, 14.47, 22.35, 11.31,  8.19,
       12.98, 16.91, 20.89, 23.4 , 26.31, 11.8 , 19.92,  6.46, 27.27,
       10.72, 10.33,  8.81, 30.75,  7.56, 25.34,  7.02, 24.37, 30.65,
        6.  , 30.79, 30.84, 28.72, 11.06,  7.21, 12.73, 11.55,  8.46,
       29.69,  6.11,  7.84,  6.67, 10.47, 30.17, 10.08, 30.94, 30.89,
       30.99, 14.03, 13.06,  6.19, 11.05, 15.49, 21.85, 10.56,  7.46,
        5.31, 14.52,  9.58, 18.45, 12.13,  8.08, 19.42,  6.83, 16.46,
       10.07, 17.47, 20.39, 25.81, 26.77, 23.87, 22.9 , 24.84, 12.61,
       14.07,  6.71,  7.96,  9.43, 10.9 , 11.98, 13.58, 16.01, 15.04,
        7.34,  6.07, 10.41,  9.92,  7.97,  7.35, 17.09,  9.44, 20.  ,
       18.06, 10.91, 11.99, 15.05,  6.08,  9.93, 12.62, 24.85, 23.88,
       14.08, 10.42,  6.72, 19.03, 16.02, 21.45, 13.59,  5.32, 25.82,
       26.3 , 22.91, 12.79, 17.99,  8.59, 21.49,  8.99, 13.99, 14.49,
       11.49, 10.99,  6.99, 26.49, 16.99, 15.59, 24.99, 10.49, 13.49,
       22.39,  7.59, 19.99,  9.49, 18.99,  7.99, 25.69, 23.99, 28.18,
       27.49, 29.67, 25.29, 24.49, 29.96, 27.79, 28.88, 26.99,  6.97,
       10.75, 12.99,  9.75,  7.39,  9.16, 20.99, 11.47,  7.89, 14.46,
       15.31, 17.27, 16.29,  8.39,  6.49, 18.25, 13.67, 25.65, 23.32,
       25.11, 26.14, 25.44, 27.34, 24.11, 21.97, 23.13, 21.18, 19.53,
       25.88, 26.57, 22.45, 20.75, 28.67, 28.99, 28.34, 28.14, 15.29,
       11.16, 16.59,  8.49, 21.48, 13.44, 10.78,  9.17, 12.88,  7.91,
       11.48, 24.24, 18.49, 14.85,  7.49,  9.8 , 20.5 , 15.77, 19.89,
       25.09, 19.48, 28.49, 26.06, 27.99, 13.19, 14.77,  6.89, 12.59,
       17.57, 10.64, 16.55, 13.18,  8.38, 11.22, 15.41,  9.76, 22.99,
       17.86, 14.48,  6.24, 25.99,  7.26, 21.99, 27.31, 18.2 , 28.69,
        8.24, 11.39, 25.49, 11.44, 15.99, 12.74, 14.99,  7.24, 22.74,
       26.24, 29.99, 29.49, 24.74, 30.49, 30.74, 27.88, 14.33, 12.05,
        8.18,  9.99, 16.9 , 18.55, 11.53, 14.65, 13.33, 12.69, 19.19,
       12.29, 15.61, 25.78, 19.52, 24.5 ,  6.39,  5.93,  6.92, 21.67,
       20.49,  6.68, 18.84, 25.8 , 25.57, 25.89, 25.83, 16.49, 13.66,
       12.39, 18.54,  8.67, 17.14,  6.03, 14.31, 19.24,  7.07,  6.62,
        7.62, 16.24, 12.85, 13.53,  8.9 ,  9.67, 14.98, 19.97, 13.98,
        7.9 , 19.22, 22.4 , 23.7 , 24.08, 17.76, 21.7 , 16.2 , 15.1 ,
       19.2 , 14.3 , 20.2 , 17.1 , 23.1 , 21.  ,  8.6 ,  9.25, 22.2 ,
       22.7 , 15.22, 13.68, 21.6 , 16.78, 18.85,  9.71, 17.56, 15.88,
       13.05, 12.35, 23.5 , 20.8 , 21.15, 24.89, 20.31, 25.28, 10.16,
       15.8 , 12.12, 19.05, 18.75, 19.72, 17.77, 14.09, 11.14, 13.11,
       23.28, 23.76, 21.98, 23.63, 23.83, 24.7 , 22.95, 22.47, 24.83,
       10.74, 15.81, 22.78, 23.33, 24.2 , 24.76, 24.33, 23.26, 24.52,
       15.27,  9.91, 20.3 , 15.96, 12.42, 17.58, 11.71, 19.91, 10.65,
       16.77, 14.27,  7.51, 21.28, 23.52, 18.64, 23.91, 22.06, 14.28,
       12.49, 18.24,  7.69, 13.35, 10.15, 23.43, 11.67, 22.15,  7.12,
       17.5 , 14.64, 13.65, 14.16, 19.47, 18.92, 22.11,  5.99, 18.79,
       15.23, 14.79,  5.42, 10.59, 17.49, 15.62, 21.36, 19.29, 18.39,
       16.89, 20.62, 22.85, 19.69, 20.25, 23.22, 21.74, 22.48, 23.59,
       18.07, 11.63,  7.42, 19.39, 16.11, 17.54, 22.64, 13.84, 17.19,
       12.87, 20.69, 21.82, 19.79, 22.94, 24.59, 24.4 , 14.82, 14.17,
        7.29, 17.88, 20.11, 17.51, 13.43, 14.91, 15.28, 15.65, 11.11,
       10.37, 16.4 ,  7.66, 10.  , 18.62,  5.79,  9.63, 14.54, 12.68,
       19.36, 13.8 , 21.59, 20.85, 21.22, 19.74, 20.48,  6.91, 12.23,
       10.36,  6.17,  6.54, 16.69, 15.95,  8.88,  9.62, 16.32, 14.83,
       13.72, 20.03, 17.8 , 15.2 , 15.57, 19.66, 17.06, 18.17, 17.43,
       20.4 , 20.77, 18.91, 21.14, 17.44, 13.23,  7.88, 11.12, 13.61,
       10.38, 17.93, 15.58, 14.84, 15.21,  6.76, 11.86,  7.14, 14.35,
       16.82, 14.72, 16.45, 18.67, 20.53, 19.41, 20.16, 21.27, 18.3 ,
       19.04, 20.9 , 21.64, 10.25, 10.62, 13.48, 14.59, 16.07, 15.7 ,
        9.88, 11.36, 15.33, 13.85, 14.96, 14.22,  7.74, 13.22, 13.57,
       17.04, 14.61,  8.94, 12.18, 11.83, 16.35, 13.92, 14.26, 19.13,
       12.53, 16.7 , 16.  , 17.39, 18.09,  7.4 , 18.43, 17.74,  7.05,
       20.52, 20.86, 18.78, 21.21, 19.82, 20.17, 13.16,  8.  , 13.47,
       12.21, 16.63,  9.32, 12.84, 11.26, 15.68, 15.37, 10.95, 11.89,
       14.11, 13.79,  7.68, 11.58,  7.37, 16.95, 18.53, 14.74, 14.42,
       18.21, 17.26, 17.9 , 19.16,  9.38, 12.72, 13.36, 11.46, 10.51,
        9.07, 13.04, 11.78, 12.41, 10.83, 12.09, 17.46, 17.15, 15.25,
       10.2 , 14.93, 18.72, 14.62,  8.32, 14.12, 10.96, 10.01, 12.86,
       11.28, 11.59,  8.63, 12.54, 12.22, 11.91, 15.38, 16.96, 13.17,
        9.7 , 16.33, 14.75, 15.07, 10.71, 11.34, 10.39, 13.87, 11.03,
       11.66, 13.24,  9.45, 13.55, 11.97, 12.92, 15.45, 14.5 , 14.18,
       15.13, 16.08, 15.76, 17.03, 17.34, 16.71,  9.83, 13.62, 10.46,
        9.51,  9.2 , 13.3 ,  7.75, 12.36, 12.67, 11.72, 13.93,  8.07,
        7.43, 12.04, 14.25, 14.88, 11.41, 11.09, 10.14, 16.15, 15.83,
       18.36,  9.64,  9.96,  9.01,  9.33, 11.54, 12.17, 12.8 , 14.38,
       13.75, 14.7 , 13.12, 10.28,  8.7 , 14.67, 15.01, 17.78, 16.83,
       17.59, 14.43, 16.65, 17.91, 17.28, 18.86, 18.61, 17.66, 18.29,
       18.04, 14.57, 17.72, 15.51, 17.41, 17.22, 16.28])

In [26]:
# loan.int_rate = loan.int_rate.str[:-1].astype(float)

In [27]:
loan["credit_score"] = loan.sub_grade.apply(subgrade_score)

In [28]:
loan.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,zip_code_prefix,earliest_cr_line_date,credit_history,credit_history_years,emp_length_years,credit_score
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,Chef,10+ years,RENT,55000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,109xx,NY,18.24,0.0,Apr-2001,1.0,0.0,45.0,9.0,1.0,4341,10.3,34.0,w,2386.02,2386.02,167.02,167.02,113.98,53.04,0.0,0.0,0.0,Feb-2019,84.92,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,16901.0,2.0,2.0,1.0,2.0,2.0,12560.0,69.0,2.0,7.0,2137.0,28.0,42000.0,1.0,11.0,2.0,9.0,1878.0,34360.0,5.9,0.0,0.0,140.0,212.0,1.0,1.0,0.0,1.0,NaN,2.0,NaN,0.0,2.0,5.0,3.0,3.0,16.0,7.0,18.0,5.0,9.0,0.0,0.0,0.0,3.0,100.0,0.0,1.0,0.0,60124.0,16901.0,36500.0,18124.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,109.0,2001-04-01,6331 days,17.333333,10.0,2.0
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,Postmaster,10+ years,MORTGAGE,90000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,713xx,LA,26.52,0.0,Jun-1987,0.0,71.0,75.0,13.0,1.0,12315,24.2,44.0,w,29387.75,29387.75,1507.11,1507.11,612.25,894.86,0.0,0.0,0.0,Feb-2019,777.23,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,1208.0,321915.0,4.0,4.0,2.0,3.0,3.0,87153.0,88.0,4.0,5.0,998.0,57.0,50800.0,2.0,15.0,2.0,10.0,24763.0,13761.0,8.3,0.0,0.0,163.0,378.0,4.0,3.0,3.0,4.0,NaN,4.0,NaN,0.0,2.0,4.0,4.0,9.0,27.0,8.0,14.0,4.0,13.0,0.0,0.0,0.0,6.0,95.0,0.0,1.0,0.0,372872.0,99468.0,15000.0,94072.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,713.0,1987-06-01,11384 days,31.167693,10.0,3.2
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,490xx,MI,10.51,0.0,Apr-2011,0.0,0.0,0.0,8.0,0.0,4599,19.1,13.0,w,4787.21,4787.21,353.89,353.89,212.79,141.10,0.0,0.0,0.0,Feb-2019,180.69,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,110299.0,0.0,1.0,0.0,2.0,14.0,7150.0,72.0,0.0,2.0,0.0,35.0,24100.0,1.0,5.0,0.0,4.0,18383.0,13800.0,0.0,0.0,0.0,87.0,92.0,15.0,14.0,2.0,77.0,NaN,14.0,NaN,0.0,0.0,3.0,3.0,3.0,4.0,6.0,7.0,3.0,8.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,136927.0,11749.0,13800.0,10000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,490.0,2011-04-01,2679 days,7.334702,6.0,3.0
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,IT Supervisor,10+ years,MORTGAGE,92000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,985xx,WA,16.74,0.0,Feb-2006,0.0,0.0,0.0,10.0,0.0,5468,78.1,13.0,w,3831.93,3831.93,286.71,286.71,168.07,118.64,0.0,0.0,0.0,Feb-2019,146.51,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,686.0,305049.0,1.0,5.0,3.0,5.0,5.0,30683.0,68.0,0.0,0.0,3761.0,70.0,7000.0,2.0,4.0,3.0,5.0,30505.0,1239.0,75.2,0.0,0.0,62.0,154.0,64.0,5.0,3.0,64.0,NaN,5.0,NaN,0.0,1.0,2.0,1.0,2.0,7.0,2.0,3.0,2.0,10.0,0.0,0.0,0.0,3.0,100.0,100.0,0.0,0.0,385183.0,36151.0,5000.0,44984.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,985.0,2006-02-01,4564 days,12.495551,10.0,3.2
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,Mechanic,10+ years,MORTGAGE,57250.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,212xx,MD,26.35,0.0,Dec-2000,0.0,0.0,0.0,12.0,0.0,829,3.6,26.0,w,29339.02,29339.02,1423.21,1423.21,660.98,762.23,0.0,0.0,0.0,Feb-2019,731.78,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,116007.0,3.0,5.0,3.0,5.0,4.0,28845.0,89.0,2.0,4.0,516.0,54.0,23100.0,1.0,0.0,0.0,9.0,9667.0,8471.0,8.9,0.0,0.0,53.0,216.0,2.0,2.0,2.0,2.0,NaN,13.0,NaN,0.0,2.0,2.0,3.0,8.0,9.0,6.0,15.0,2.0,12.0,0.0,0.0,0.0,5.0,92.3,0.0,0.0,0.0,157548.0,29674.0,9300.0,32332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,212.0,2000-12-01,6452 days,17.664613,10.0,2.6

In [29]:
loan.issue_d.min()

'Apr-2008'

In [30]:
# Convert the loan issue date to a datetime in order to speed up processing
loan["issue_date"] = pd.to_datetime(loan.issue_d, format="%b-%Y")

In [31]:
loan["issue_date"]

0         2018-12-01
1         2018-12-01
2         2018-12-01
3         2018-12-01
4         2018-12-01
             ...
2260663   2017-10-01
2260664   2017-10-01
2260665   2017-10-01
2260666   2017-10-01
2260667   2017-10-01
Name: issue_date, Length: 2260668, dtype: datetime64[ns]

In [32]:
loan.earliest_cr_line_date = pd.to_datetime(loan.earliest_cr_line, format="%b-%Y").fillna(loan.issue_date)

In [33]:
loan.earliest_cr_line_date

0         2001-04-01
1         1987-06-01
2         2011-04-01
3         2006-02-01
4         2000-12-01
             ...
2260663   2004-01-01
2260664   2003-03-01
2260665   1995-02-01
2260666   2003-07-01
2260667   2014-04-01
Name: earliest_cr_line_date, Length: 2260668, dtype: datetime64[ns]

In [34]:
pd.to_datetime(['Apr-2008'], format="%b-%Y")

DatetimeIndex(['2008-04-01'], dtype='datetime64[ns]', freq=None)

In [35]:
# Create a predictor/column with the year the loan was issued
loan["issue_date_year"] = loan.issue_date.dt.year

In [36]:
loan["issue_date_year"]

0          2018
1          2018
2          2018
3          2018
4          2018
           ...
2260663    2017
2260664    2017
2260665    2017
2260666    2017
2260667    2017
Name: issue_date_year, Length: 2260668, dtype: int32

In [37]:
loan["issue_date_days"] = loan.issue_date.dt.day

In [38]:
loan["issue_date_days"].nunique()

1

In [39]:
# Create a predictor/column with the date of the last payment
loan["last_pymnt_date"] = pd.to_datetime(loan.last_pymnt_d, format="%b-%Y")

In [40]:
loan["last_pymnt_date"]

0         2019-02-01
1         2019-02-01
2         2019-02-01
3         2019-02-01
4         2019-02-01
             ...
2260663   2019-02-01
2260664   2018-08-01
2260665   2019-02-01
2260666   2019-02-01
2260667   2019-02-01
Name: last_pymnt_date, Length: 2260668, dtype: datetime64[ns]

In [41]:
# Create a feature/column with the actual loan length
# This is not the same as the planned loan length
loan["loan_length"] = loan["last_pymnt_date"] - loan["issue_date"]

In [69]:
loan.loan_length.nunique()

282

In [70]:
loan.loan_length

0          62 days
1          62 days
2          62 days
3          62 days
4          62 days
            ...
2260663   488 days
2260664   304 days
2260665   488 days
2260666   488 days
2260667   488 days
Name: loan_length, Length: 2260668, dtype: timedelta64[ns]

In [42]:
# Clean the data for the predictor/column loan length term
loan["loan_length_term"] = loan.loan_length.fillna(loan.loan_length)

In [43]:
# Clean the data for the predictor/column loan length in days
loan["loan_length_days"] = loan.loan_length_term.dt.days.fillna(1)

In [44]:
# Check that the dates have been properly changed
loan[["last_pymnt_date", "issue_date", "loan_length","grade","term","loan_status"]].head()

  last_pymnt_date issue_date loan_length grade        term loan_status
0      2019-02-01 2018-12-01     62 days     C   36 months     Current
1      2019-02-01 2018-12-01     62 days     D   60 months     Current
2      2019-02-01 2018-12-01     62 days     D   36 months     Current
3      2019-02-01 2018-12-01     62 days     D   36 months     Current
4      2019-02-01 2018-12-01     62 days     C   60 months     Current

In [45]:
loan.issue_date.describe()

count                          2260668
mean     2016-05-02 18:48:08.652734976
min                2007-06-01 00:00:00
25%                2015-04-01 00:00:00
50%                2016-07-01 00:00:00
75%                2017-11-01 00:00:00
max                2018-12-01 00:00:00
Name: issue_date, dtype: object

In [46]:
loan.select_dtypes('number')

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,url,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,annual_inc_joint,dti_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term,zip_code_prefix,credit_history,credit_history_years,emp_length_years,credit_score,issue_date_year,issue_date_days,loan_length,loan_length_term,loan_length_days
0,NaN,NaN,2500,2500,2500.0,13.56,84.92,55000.0,NaN,18.24,0.0,1.0,0.0,45.0,9.0,1.0,4341,10.3,34.0,2386.02,2386.02,167.020000,167.02,113.98,53.04,0.0,0.0,0.0,84.92,0.0,NaN,1,NaN,NaN,0.0,0.0,16901.0,2.0,2.0,1.0,2.0,2.0,12560.0,69.0,2.0,7.0,2137.0,28.0,42000.0,1.0,11.0,2.0,9.0,1878.0,34360.0,5.9,0.0,0.0,140.0,212.0,1.0,1.0,0.0,1.0,NaN,2.0,NaN,0.0,2.0,5.0,3.0,3.0,16.0,7.0,18.0,5.0,9.0,0.0,0.0,0.0,3.0,100.0,0.0,1.0,0.0,60124.0,16901.0,36500.0,18124.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109.0,6331 days,17.333333,10.000000,2.0,2018,1,62 days,62 days,62.0
1,NaN,NaN,30000,30000,30000.0,18.94,777.23,90000.0,NaN,26.52,0.0,0.0,71.0,75.0,13.0,1.0,12315,24.2,44.0,29387.75,29387.75,1507.110000,1507.11,612.25,894.86,0.0,0.0,0.0,777.23,0.0,NaN,1,NaN,NaN,0.0,1208.0,321915.0,4.0,4.0,2.0,3.0,3.0,87153.0,88.0,4.0,5.0,998.0,57.0,50800.0,2.0,15.0,2.0,10.0,24763.0,13761.0,8.3,0.0,0.0,163.0,378.0,4.0,3.0,3.0,4.0,NaN,4.0,NaN,0.0,2.0,4.0,4.0,9.0,27.0,8.0,14.0,4.0,13.0,0.0,0.0,0.0,6.0,95.0,0.0,1.0,0.0,372872.0,99468.0,15000.0,94072.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,713.0,11384 days,31.167693,10.000000,3.2,2018,1,62 days,62 days,62.0
2,NaN,NaN,5000,5000,5000.0,17.97,180.69,59280.0,NaN,10.51,0.0,0.0,0.0,0.0,8.0,0.0,4599,19.1,13.0,4787.21,4787.21,353.890000,353.89,212.79,141.10,0.0,0.0,0.0,180.69,0.0,NaN,1,NaN,NaN,0.0,0.0,110299.0,0.0,1.0,0.0,2.0,14.0,7150.0,72.0,0.0,2.0,0.0,35.0,24100.0,1.0,5.0,0.0,4.0,18383.0,13800.0,0.0,0.0,0.0,87.0,92.0,15.0,14.0,2.0,77.0,NaN,14.0,NaN,0.0,0.0,3.0,3.0,3.0,4.0,6.0,7.0,3.0,8.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,136927.0,11749.0,13800.0,10000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,490.0,2679 days,7.334702,6.000000,3.0,2018,1,62 days,62 days,62.0
3,NaN,NaN,4000,4000,4000.0,18.94,146.51,92000.0,NaN,16.74,0.0,0.0,0.0,0.0,10.0,0.0,5468,78.1,13.0,3831.93,3831.93,286.710000,286.71,168.07,118.64,0.0,0.0,0.0,146.51,0.0,NaN,1,NaN,NaN,0.0,686.0,305049.0,1.0,5.0,3.0,5.0,5.0,30683.0,68.0,0.0,0.0,3761.0,70.0,7000.0,2.0,4.0,3.0,5.0,30505.0,1239.0,75.2,0.0,0.0,62.0,154.0,64.0,5.0,3.0,64.0,NaN,5.0,NaN,0.0,1.0,2.0,1.0,2.0,7.0,2.0,3.0,2.0,10.0,0.0,0.0,0.0,3.0,100.0,100.0,0.0,0.0,385183.0,36151.0,5000.0,44984.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,985.0,4564 days,12.495551,10.000000,3.2,2018,1,62 days,62 days,62.0
4,NaN,NaN,30000,30000,30000.0,16.14,731.78,57250.0,NaN,26.35,0.0,0.0,0.0,0.0,12.0,0.0,829,3.6,26.0,29339.02,29339.02,1423.210000,1423.21,660.98,762.23,0.0,0.0,0.0,731.78,0.0,NaN,1,NaN,NaN,0.0,0.0,116007.0,3.0,5.0,3.0,5.0,4.0,28845.0,89.0,2.0,4.0,516.0,54.0,23100.0,1.0,0.0,0.0,9.0,9667.0,8471.0,8.9,0.0,0.0,53.0,216.0,2.0,2.0,2.0,2.0,NaN,13.0,NaN,0.0,2.0,2.0,3.0,8.0,9.0,6.0,15.0,2.0,12.0,0.0,0.0,0.0,5.0,92.3,0.0,0.0,0.0,157548.0,29674.0,9300.0,32332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,212.0,6452 days,17.664613,10.000000,2.6,2018,1,62 days,62 days,62.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260663,NaN,NaN,12000,12000,12000.0,14.08,279.72,58000.0,NaN,20.88,0.0,0.0,0.0,0.0,12.0,0.0,9592,39.2,34.0,8687.20,8687.20,5360.960000,5360.96,3312.80,2048.16,0.0,0.0,0.0,279.72,0.0,NaN,1,NaN,NaN,0.0,7921.0,45212.0,2.0,2.0,0.0,1.0,24.0,35620.0,36.0,3.0,4.0,4052.0,38.0,24500.0,2.0,2.0,1.0,5.0,4110.0,1807.0,70.9,0.0,0.0,157.0,164.0,1.0,1.0,2.0,9.0,NaN,9.0,NaN,0.0,2.0,4.0,3.0,9.0,11.0,10.0,21.0,4.0,12.0,0.0,0.0,0.0,3.0,100.0,66.7,0.0,0.0,73948.0,45212.0,6200.0,49448.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.0,5326 days,14.581793,10.000000,2.4,2017,1,488 days,488 days,488.0
2260664,NaN,NaN,12000,12000,12000.0,25.82,358.01,30000.0,NaN,19.28,3.0,1.0,13.0,0.0,10.0,0.0,3497,20.2,26.0,0.00,0.00,14499.802172,14499.80,12000.00,2499.80,0.0,0.0,0.0,182.74,0.0,46.0,1,135000.0,7.36,0.0,550.0,346404.0,0.0,1.0,1.0,1.0,8.0,9431.0,78.0,0.0,3.0,2238.0,44.0,17300.0,5.0,1.0,7.0,4.0,34640.0,9162.0,19.6,0.0,0.0,163.0,174.0,16.0,8.0,4.0,141.0,46.0,0.0,17.0,2.0,1.0,4.0,2.0,5.0,4.0,7.0,18.0,4.0,10.0,0.0,0.0,0.0,1.0,76.9,50.0,0.0,0.0,382275.0,12928.0,11400.0,12125.0,13710.0,1.0,4.0,11.0,71.6,1.0,17.0,0.0,0.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,971.0,5632 days,15.419576,1.000000,4.6,2017,1,304 days,304 days,304.0
2260665,NaN,NaN,10000,10000,10000.0,11.99,332.10,64000.0,NaN,12.96,0.0,0.0,0.0,0.0,6.0,0.0,7094,70.9,13.0,5993.27,5993.27,5306.940000,5306.94,4006.73,1300.21,0.0,0.0,0.0,332.10,1.0,NaN,1,NaN,NaN,0.0,77.0,189735.0,1.0,2.0,1.0,2.0,3.0,29354.0,100.0,0.0,1.0,1864.0,93.0,10000.0,0.0,0.0,3.0,3.0,31623.0,136.0,93.2,0.0,0.0,134.0,271.0,15.0,3.0,3.0,111.0,NaN,3.0,NaN,0.0,1.0,3.0,1.0,2.0,4.0,3.0,6.0,3.0,6.0,0.0,0.0,0.0,1.0,100.0,100.0,0.0,0.0,203417.0,36448.0,2000.0,29317.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,603.0,8582 days,23.496235,10.000000,1.8,2017,1,488 days,488 days,488.0
2260666,NaN,NaN,12000,12000,12000.0,21.45,327.69,60000.0,NaN,30.82,2.0,1.0,7.0,0.0,8.0,0.0,12927,34.9,17.0,9924.69,9924.69,5207.290000,5207.29,2075.31,3131.98,0.0,0.0,0.0,327.69,0.0,NaN,1,NaN,NaN,0.0,535.0,65238.0,2.0,4.0,2.0,3.0,4.0,52311.0,64.0,1.0,2.0,2406.0,55.0,37000.0,0.0,12.0,4.0,5.0,8155.0,18789.0,14.6,0.0,0.0,170.0,67.0,4.0,4.0,0.0,16.0,9.0,5.0,7.0,0.0,2.0,3.0,2.0,3.0,12.0,4.0,5.0,3.0,8.0,0.0,0.0,0.0,3.0,88.2,0.0,0.0,0.0,118975.0,65238.0,22000.0,81975.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,996.0,5510 days,15.085558,6.021241,3.8,2017,1,488 days,488 days,488.0
2260667,NaN,NaN,16550,16550,16550.0,21.45,451.94,60000.0,NaN,18.40,0.0,1.0,0.0,0.0,13.0,0.0,25760,50.8,14.0,13541.01,13541.01,7355.500000,7355.50,3008.99,4346.51,0.0,0.0,0.0,500.00,0.0,NaN,1,NaN,NaN,0.0,0.0,25760.0,2.0,0.0,0.0,0.0,NaN,0.0,NaN,3.0,8.0,6158.0,51.0,50700.0,0.0,0.0,2.0,8.0,1982.0,9816.0,49.7,0.0,0.0,NaN,41.0,3.0,3.0,0.0,10.0,NaN,0.0,NaN,0.0,5.0,12.0,5.0,5.0,0.0,13.0,14.0,12.0,13.0,0.0,0.0,0.0,3.0,100.0,20.0,0.0,0.0,50700.0,25760.0,19500.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,112.0,1583 days,4.334018,3.000000,3.8,2017,1,488 days,488 days,488.0

# Calculate the Profitability of the Loans¶

#### This will be used as the y variable¶

In [108]:
# New column/predictor percentage of the revolving credit utilized
loan["revol_util_perc"] = loan.revol_util.astype(str).apply(extract_number)
loan["revol_util_perc"] = loan["revol_util_perc"].fillna(np.mean(loan.revol_util_perc))

In [109]:
loan.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,zip_code_prefix,earliest_cr_line_date,credit_history,credit_history_years,emp_length_years,credit_score,issue_date,issue_date_year,issue_date_days,last_pymnt_date,loan_length,loan_length_term,loan_length_days,revol_util_perc,term_months,term_days,apy
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,Chef,10+ years,RENT,55000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,109xx,NY,18.24,0.0,Apr-2001,1.0,0.0,45.0,9.0,1.0,4341,10.3,34.0,w,2386.02,2386.02,167.02,167.02,113.98,53.04,0.0,0.0,0.0,Feb-2019,84.92,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,16901.0,2.0,2.0,1.0,2.0,2.0,12560.0,69.0,2.0,7.0,2137.0,28.0,42000.0,1.0,11.0,2.0,9.0,1878.0,34360.0,5.9,0.0,0.0,140.0,212.0,1.0,1.0,0.0,1.0,NaN,2.0,NaN,0.0,2.0,5.0,3.0,3.0,16.0,7.0,18.0,5.0,9.0,0.0,0.0,0.0,3.0,100.0,0.0,1.0,0.0,60124.0,16901.0,36500.0,18124.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,109.0,2001-04-01,6331 days,17.333333,10.0,2.0,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,10.0,36,1080 days,-1.0
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,Postmaster,10+ years,MORTGAGE,90000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,713xx,LA,26.52,0.0,Jun-1987,0.0,71.0,75.0,13.0,1.0,12315,24.2,44.0,w,29387.75,29387.75,1507.11,1507.11,612.25,894.86,0.0,0.0,0.0,Feb-2019,777.23,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,1208.0,321915.0,4.0,4.0,2.0,3.0,3.0,87153.0,88.0,4.0,5.0,998.0,57.0,50800.0,2.0,15.0,2.0,10.0,24763.0,13761.0,8.3,0.0,0.0,163.0,378.0,4.0,3.0,3.0,4.0,NaN,4.0,NaN,0.0,2.0,4.0,4.0,9.0,27.0,8.0,14.0,4.0,13.0,0.0,0.0,0.0,6.0,95.0,0.0,1.0,0.0,372872.0,99468.0,15000.0,94072.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,713.0,1987-06-01,11384 days,31.167693,10.0,3.2,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,24.0,60,1800 days,-1.0
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,490xx,MI,10.51,0.0,Apr-2011,0.0,0.0,0.0,8.0,0.0,4599,19.1,13.0,w,4787.21,4787.21,353.89,353.89,212.79,141.10,0.0,0.0,0.0,Feb-2019,180.69,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,110299.0,0.0,1.0,0.0,2.0,14.0,7150.0,72.0,0.0,2.0,0.0,35.0,24100.0,1.0,5.0,0.0,4.0,18383.0,13800.0,0.0,0.0,0.0,87.0,92.0,15.0,14.0,2.0,77.0,NaN,14.0,NaN,0.0,0.0,3.0,3.0,3.0,4.0,6.0,7.0,3.0,8.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,136927.0,11749.0,13800.0,10000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,490.0,2011-04-01,2679 days,7.334702,6.0,3.0,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,19.0,36,1080 days,-1.0
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,IT Supervisor,10+ years,MORTGAGE,92000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,985xx,WA,16.74,0.0,Feb-2006,0.0,0.0,0.0,10.0,0.0,5468,78.1,13.0,w,3831.93,3831.93,286.71,286.71,168.07,118.64,0.0,0.0,0.0,Feb-2019,146.51,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,686.0,305049.0,1.0,5.0,3.0,5.0,5.0,30683.0,68.0,0.0,0.0,3761.0,70.0,7000.0,2.0,4.0,3.0,5.0,30505.0,1239.0,75.2,0.0,0.0,62.0,154.0,64.0,5.0,3.0,64.0,NaN,5.0,NaN,0.0,1.0,2.0,1.0,2.0,7.0,2.0,3.0,2.0,10.0,0.0,0.0,0.0,3.0,100.0,100.0,0.0,0.0,385183.0,36151.0,5000.0,44984.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,985.0,2006-02-01,4564 days,12.495551,10.0,3.2,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,78.0,36,1080 days,-1.0
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,Mechanic,10+ years,MORTGAGE,57250.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,212xx,MD,26.35,0.0,Dec-2000,0.0,0.0,0.0,12.0,0.0,829,3.6,26.0,w,29339.02,29339.02,1423.21,1423.21,660.98,762.23,0.0,0.0,0.0,Feb-2019,731.78,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,116007.0,3.0,5.0,3.0,5.0,4.0,28845.0,89.0,2.0,4.0,516.0,54.0,23100.0,1.0,0.0,0.0,9.0,9667.0,8471.0,8.9,0.0,0.0,53.0,216.0,2.0,2.0,2.0,2.0,NaN,13.0,NaN,0.0,2.0,2.0,3.0,8.0,9.0,6.0,15.0,2.0,12.0,0.0,0.0,0.0,5.0,92.3,0.0,0.0,0.0,157548.0,29674.0,9300.0,32332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,212.0,2000-12-01,6452 days,17.664613,10.0,2.6,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,3.0,60,1800 days,-1.0

In [90]:
# Calculate the length of the loan
loan["term_months"] = [extract_number(s) for s in loan.term]

In [91]:
loan.term_months.unique()

array([36, 60], dtype=int64)

In [92]:
loan["term_days"] = pd.to_timedelta(loan.term_months*30, unit='D')

In [93]:
loan.term_days.unique()

<TimedeltaArray>
['1080 days', '1800 days']
Length: 2, dtype: timedelta64[ns]

In [94]:
loan.loan_length_days

0           62.0
1           62.0
2           62.0
3           62.0
4           62.0
           ...
2260663    488.0
2260664    304.0
2260665    488.0
2260666    488.0
2260667    488.0
Name: loan_length_days, Length: 2260668, dtype: float64

In [95]:
loan.loan_length_days.nunique()

283

In [127]:
# Calculate the Annual Percentage Rate
loan["apy"] = (loan.total_pymnt / loan.loan_amnt) ** (365.25/(loan.loan_length_days)) - 1

In [97]:
# In order to be able to use APY we need to remove loans with very short lengths
loan.query("loan_length_days > 60 and apy>1")[["funded_amnt", "total_pymnt", "loan_length_days", "apy", "loan_status"]]

         funded_amnt  total_pymnt  loan_length_days       apy  loan_status
538349         35000     39870.20              61.0  1.181657  Charged Off
1682281         7350      8558.46              62.0  1.451616  Charged Off
1836138        30000     35233.92              61.0  1.619266  Charged Off
1847567         3000      3404.91              61.0  1.134176  Charged Off
1883361        14400     18260.17              61.0  3.145585  Charged Off

In [98]:
loan.credit_history.head()

0    6331 days
1   11384 days
2    2679 days
3    4564 days
4    6452 days
Name: credit_history, dtype: timedelta64[ns]

In [110]:
# Completed loans are those which are either charged off or fully paid
complete = loan.query("(loan_status=='Charged Off' or loan_status=='Fully Paid') and loan_length_days > 60 and apy < 1")
complete["good_loan"] = complete.loan_status=='Fully Paid'

In [100]:
complete

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,zip_code_prefix,earliest_cr_line_date,credit_history,credit_history_years,emp_length_years,credit_score,issue_date,issue_date_year,issue_date_days,last_pymnt_date,loan_length,loan_length_term,loan_length_days,revol_util_perc,term_months,term_days,apy,good_loan
152,NaN,NaN,40000,40000,40000.0,60 months,16.14,975.71,C,C4,Assistant to the Treasurer (Payroll),< 1 year,MORTGAGE,45000.0,Verified,Dec-2018,Fully Paid,n,NaN,NaN,credit_card,Credit card refinancing,456xx,OH,50.53,0.0,Jun-2009,0.0,0.0,0.0,18.0,0.0,34971,64.5,37.0,w,0.0,0.0,40856.678960,40856.68,40000.00,856.68,0.00,0.0,0.0,Feb-2019,40910.48,NaN,Feb-2019,0.0,NaN,1,Joint App,92000.0,35.66,Verified,0.0,0.0,271068.0,2.0,8.0,3.0,4.0,5.0,126749.0,87.0,1.0,1.0,5874.0,75.0,54200.0,4.0,2.0,4.0,5.0,15059.0,14930.0,67.3,0.0,0.0,114.0,70.0,2.0,2.0,1.0,2.0,NaN,9.0,NaN,0.0,7.0,9.0,7.0,7.0,26.0,9.0,10.0,9.0,18.0,0.0,0.0,0.0,4.0,100.0,42.9,0.0,0.0,344802.0,161720.0,45700.0,167965.0,47188.0,Apr-1990,0.0,1.0,32.0,61.1,16.0,19.0,0.0,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,456.0,2009-06-01,3348 days,9.166324,1.0,2.6,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,64.0,60,1800 days,0.132965,True
170,NaN,NaN,20000,20000,20000.0,36 months,7.56,622.68,A,A3,Teacher,10+ years,MORTGAGE,100000.0,Not Verified,Dec-2018,Fully Paid,n,NaN,NaN,credit_card,Credit card refinancing,982xx,WA,18.92,0.0,Feb-1999,0.0,48.0,0.0,9.0,0.0,25416,29.9,19.0,w,0.0,0.0,20215.792430,20215.79,20000.00,215.79,0.00,0.0,0.0,Feb-2019,20228.39,NaN,Feb-2019,0.0,NaN,1,Joint App,190000.0,11.75,Not Verified,0.0,0.0,515779.0,1.0,2.0,0.0,1.0,13.0,46153.0,71.0,1.0,2.0,9759.0,39.0,85100.0,2.0,2.0,0.0,5.0,57309.0,59684.0,29.9,0.0,0.0,171.0,238.0,1.0,1.0,5.0,1.0,NaN,13.0,48.0,0.0,5.0,5.0,5.0,6.0,5.0,5.0,9.0,5.0,9.0,0.0,0.0,0.0,1.0,94.7,20.0,0.0,0.0,622183.0,71569.0,85100.0,74833.0,43287.0,Aug-1998,0.0,3.0,10.0,29.7,2.0,7.0,0.0,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,982.0,1999-02-01,7121 days,19.496235,10.0,0.4,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,29.0,36,1080 days,0.065264,True
186,NaN,NaN,4500,4500,4500.0,36 months,11.31,147.99,B,B3,Accounts Examiner III,10+ years,RENT,38500.0,Not Verified,Dec-2018,Fully Paid,n,NaN,NaN,credit_card,Credit card refinancing,786xx,TX,4.64,0.0,Dec-2003,0.0,25.0,0.0,12.0,0.0,4472,15.3,25.0,w,0.0,0.0,4549.217149,4549.22,4500.00,49.22,0.00,0.0,0.0,Feb-2019,4553.46,NaN,Feb-2019,0.0,25.0,1,Individual,NaN,NaN,NaN,0.0,306.0,29137.0,2.0,1.0,1.0,1.0,3.0,24665.0,100.0,3.0,7.0,3612.0,54.0,29200.0,0.0,3.0,3.0,8.0,2428.0,10735.0,28.9,0.0,0.0,180.0,69.0,2.0,2.0,0.0,2.0,NaN,6.0,NaN,1.0,3.0,5.0,5.0,6.0,10.0,11.0,15.0,5.0,12.0,0.0,0.0,0.0,4.0,91.7,0.0,0.0,0.0,53795.0,29137.0,15100.0,24595.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,786.0,2003-12-01,5357 days,14.666667,10.0,1.4,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,15.0,36,1080 days,0.066180,True
215,NaN,NaN,8425,8425,8425.0,36 months,27.27,345.18,E,E5,Senior Director Risk Management,3 years,MORTGAGE,450000.0,Verified,Dec-2018,Fully Paid,n,NaN,NaN,credit_card,Credit card refinancing,020xx,MA,12.37,0.0,Oct-1997,0.0,0.0,0.0,21.0,0.0,36812,65.7,37.0,w,0.0,0.0,8735.148975,8735.15,8425.00,310.15,0.00,0.0,0.0,Feb-2019,8754.30,NaN,Feb-2019,0.0,NaN,1,Joint App,515000.0,16.47,Not Verified,0.0,0.0,690320.0,0.0,6.0,1.0,6.0,12.0,152382.0,70.0,1.0,4.0,9744.0,68.0,56000.0,7.0,0.0,5.0,10.0,34516.0,11632.0,74.6,0.0,0.0,254.0,89.0,12.0,12.0,4.0,18.0,NaN,4.0,NaN,0.0,6.0,8.0,8.0,10.0,16.0,13.0,17.0,8.0,21.0,0.0,0.0,0.0,2.0,100.0,50.0,0.0,0.0,768304.0,189194.0,45800.0,189054.0,141905.0,Jun-2013,0.0,1.0,4.0,77.4,1.0,4.0,0.0,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,20.0,1997-10-01,7609 days,20.832307,3.0,4.8,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,65.0,36,1080 days,0.237352,True
369,NaN,NaN,4000,4000,4000.0,36 months,17.97,144.55,D,D1,service advisor,5 years,MORTGAGE,60000.0,Source Verified,Dec-2018,Fully Paid,n,NaN,NaN,house,Home buying,760xx,TX,19.10,0.0,Jun-2007,1.0,38.0,0.0,11.0,0.0,382,7.3,18.0,w,0.0,0.0,4049.916667,4049.92,4000.00,49.92,0.00,0.0,0.0,Feb-2019,55.91,NaN,Jan-2019,0.0,38.0,1,Individual,NaN,NaN,NaN,0.0,0.0,106556.0,2.0,3.0,3.0,4.0,1.0,45868.0,77.0,1.0,6.0,378.0,72.0,5200.0,3.0,0.0,3.0,10.0,9687.0,3818.0,9.1,0.0,0.0,57.0,31.0,12.0,1.0,2.0,15.0,NaN,2.0,NaN,1.0,2.0,2.0,5.0,5.0,9.0,7.0,7.0,2.0,11.0,0.0,0.0,0.0,4.0,88.2,0.0,0.0,0.0,127200.0,46250.0,4200.0,59474.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,760.0,2007-06-01,4079 days,11.167693,5.0,3.0,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,7.0,36,1080 days,0.075797,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260654,NaN,NaN,30000,30000,30000.0,60 months,17.09,747.03,D,D1,Senior Manager,2 years,RENT,80000.0,Not Verified,Oct-2017,Charged Off,n,NaN,NaN,debt_consolidation,Debt consolidation,112xx,NY,23.22,0.0,Dec-2001,1.0,46.0,0.0,21.0,0.0,19224,30.8,69.0,f,0.0,0.0,6047.460000,6047.46,2689.46,3358.00,0.00,0.0,0.0,Jun-2018,747.03,NaN,Dec-2018,0.0,61.0,1,Individual,NaN,NaN,NaN,0.0,0.0,196622.0,2.0,9.0,1.0,1.0,8.0,177398.0,101.0,2.0,3.0,11301.0,61.0,62400.0,0.0,0.0,1.0,4.0,9831.0,31294.0,36.5,0.0,0.0,189.0,171.0,5.0,5.0,0.0,5.0,NaN,2.0,46.0,22.0,5.0,6.0,6.0,8.0,51.0,12.0,18.0,6.0,21.0,0.0,0.0,0.0,3.0,54.9,33.3,0.0,0.0,231009.0,196622.0,49300.0,168609.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,112.0,2001-12-01,6087 days,16.665298,2.0,3.0,2017-10-01,2017,1,2018-06-01,243 days,243 days,243.0,30.0,60,1800 days,-0.909940,False
2260655,NaN,NaN,18000,18000,18000.0,60 months,30.65,589.57,F,F4,Package Delivery Driver,10+ years,MORTGAGE,77000.0,Verified,Oct-2017,Charged Off,n,NaN,NaN,debt_consolidation,Debt consolidation,799xx,TX,8.08,0.0,Sep-2004,1.0,38.0,0.0,9.0,0.0,10100,45.1,15.0,w,0.0,0.0,5393.400000,5393.40,1110.53,4164.95,117.92,0.0,0.0,Aug-2018,619.05,NaN,Jan-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,265.0,324621.0,5.0,1.0,1.0,1.0,4.0,6925.0,98.0,3.0,3.0,3358.0,59.0,22400.0,0.0,3.0,7.0,6.0,36069.0,7083.0,48.7,0.0,0.0,156.0,52.0,4.0,4.0,1.0,5.0,38.0,4.0,38.0,0.0,3.0,5.0,4.0,4.0,7.0,6.0,6.0,5.0,9.0,0.0,0.0,0.0,5.0,93.3,50.0,0.0,0.0,338546.0,18113.0,13800.0,7058.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,799.0,2004-09-01,5082 days,13.913758,10.0,5.6,2017-10-01,2017,1,2018-08-01,304 days,304 days,304.0,45.0,60,1800 days,-0.764965,False
2260656,NaN,NaN,17950,17950,17950.0,60 months,30.17,582.62,F,F3,Head Custodian,10+ years,MORTGAGE,53758.0,Source Verified,Oct-2017,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,600xx,IL,33.24,0.0,Dec-2000,1.0,0.0,80.0,11.0,1.0,5959,35.9,24.0,f,0.0,0.0,20803.775467,20803.78,17950.00,2853.78,0.00,0.0,0.0,Apr-2018,17965.90,NaN,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,156247.0,0.0,3.0,1.0,1.0,11.0,30693.0,49.0,1.0,4.0,2413.0,46.0,16600.0,1.0,1.0,2.0,5.0,15625.0,1587.0,60.3,0.0,0.0,109.0,201.0,11.0,11.0,3.0,16.0,NaN,0.0,NaN,0.0,1.0,5.0,1.0,4.0,7.0,7.0,14.0,5.0,11.0,0.0,0.0,0.0,2.0,100.0,0.0,1.0,0.0,203667.0,36652.0,4000.0,63002.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,600.0,2000-12-01,6452 days,17.664613,10.0,5.4,2017-10-01,2017,1,2018-04-01,182 days,182 days,182.0,35.0,60,1800 days,0.344607,True
2260658,NaN,NaN,15000,15000,15000.0,60 months,16.02,364.94,C,C5,Instructional Designer,< 1 year,RENT,85000.0,Verified,Oct-2017,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,119xx,NY,14.66,0.0,Mar-2001,3.0,36.0,0.0,19.0,0.0,6988,24.8,87.0,w,0.0,0.0,16112.317714,16112.32,15000.00,1112.32,0.00,0.0,0.0,Mar-2018,14613.69,NaN,Feb-2019,0.0,36.0,1,Individual,NaN,NaN,NaN,0.0,4199.0,239081.0,5.0,5.0,3.0,7.0,4.0,232093.0,70.0,4.0,10.0,2534.0,52.0,28200.0,1.0,2.0,7.0,17.0,17077.0,17477.0,23.7,0.0,0.0,191.0,198.0,0.0,0.0,1.0,2.0,36.0,0.0,36.0,7.0,4.0,6.0,8.0,17.0,55.0,13.0,31.0,6.0,19.0,0.0,0.0,0.0,7.0,89.0,0.0,0.0,0.0,267274.0,239081.0,22900.0,239074.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,119.0,2001-03-01,6362 days,17.418207,1.0,2.8,2017-10-01,2017,1,2018-03-01,151 days,151 days,151.0,24.0,60,1800 days,0.188903,True
2260664,NaN,NaN,12000,12000,12000.0,60 months,25.82,358.01,E,E4,Skilled Labor,< 1 year,MORTGAGE,30000.0,Not Verified,Oct-2017,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,971xx,OR,19.28,3.0,Mar-2003,1.0,13.0,0.0,10.0,0.0,3497,20.2,26.0,w,0.0,0.0,14499.802172,14499.80,12000.00,2499.80,0.00,0.0,0.0,Aug-2018,182.74,NaN,Sep-2017,0.0,46.0,1,Joint App,135000.0,7.36,Not Verified,0.0,550.0,346404.0,0.0,1.0,1.0,1.0,8.0,9431.0,78.0,0.0,3.0,2238.0,44.0,17300.0,5.0,1.0,7.0,4.0,34640.0,9162.0,19.6,0.0,0.0,163.0,174.0,16.0,8.0,4.0,141.0,46.0,0.0,17.0,2.0,1.0,4.0,2.0,5.0,4.0,7.0,18.0,4.0,10.0,0.0,0.0,0.0,1.0,76.9,50.0,0.0,0.0,382275.0,12928.0,11400.0,12125.0,13710.0,Apr-2003,1.0,4.0,11.0,71.6,1.0,17.0,0.0,0.0,7.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,971.0,2003-03-01,5632 days,15.419576,1.0,4.6,2017-10-01,2017,1,2018-08-01,304 days,304 days,304.0,20.0,60,1800 days,0.255274,True

In [101]:
# Overview of the loans that have been completed: charged off or fully repaid
complete.describe()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,url,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,annual_inc_joint,dti_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term,zip_code_prefix,earliest_cr_line_date,credit_history,credit_history_years,emp_length_years,credit_score,issue_date,issue_date_year,issue_date_days,last_pymnt_date,loan_length,loan_length_term,loan_length_days,revol_util_perc,term_months,term_days,apy
count,0.0,0.0,1.261477e+06,1.261477e+06,1.261477e+06,1.261477e+06,1.261477e+06,1.261477e+06,0.0,1.261477e+06,1.261477e+06,1.261477e+06,1.261477e+06,1.261477e+06,1.261477e+06,1.261477e+06,1.261477e+06,1.260719e+06,1.261477e+06,1261477.0,1261477.0,1.261477e+06,1.261477e+06,1.261477e+06,1.261477e+06,1.261477e+06,1.261477e+06,1.261477e+06,1.261477e+06,1.261421e+06,331904.000000,1261477.0,2.127400e+04,21272.000000,1.261477e+06,1.194704e+06,1.194704e+06,468680.000000,468681.000000,468681.000000,468681.000000,456706.000000,4.686810e+05,406806.000000,468681.000000,468681.000000,468681.000000,468637.000000,1.194704e+06,468681.000000,468680.000000,468680.000000,1.214766e+06,1.194687e+06,1.202078e+06,1.201371e+06,1.261421e+06,1.261477e+06,1.159282e+06,1.194703e+06,1.194703e+06,1.194704e+06,1.214766e+06,1.202922e+06,299793.000000,1.095864e+06,422387.000000,1.194704e+06,1.194704e+06,1.194704e+06,1.206279e+06,1.194704e+06,1.194704e+06,1.194704e+06,1.194703e+06,1.194704e+06,1.206279e+06,1.148067e+06,1.194704e+06,1.194704e+06,1.194704e+06,1.194550e+06,1.201678e+06,1.260784e+06,1.261438e+06,1.194704e+06,1.214766e+06,1.214766e+06,1.194704e+06,14716.000000,14717.000000,14717.000000,14717.000000,14474.000000,14717.000000,14717.000000,14717.000000,14717.000000,5267.000000,5331.0,5331.000000,5331.0,5331.000000,3433.000000,5331.00000,5331.000000,31722.000000,31722.000000,31722.000000,1.261476e+06,1261477,1261477,1.261477e+06,1.261477e+06,1.261477e+06,1261477,1.261477e+06,1261477.0,1261477,1261477,1261477,1.261477e+06,1.261477e+06,1.261477e+06,1261477,1.261477e+06
mean,NaN,NaN,1.442732e+04,1.441848e+04,1.439536e+04,1.321599e+01,4.383642e+02,7.606765e+04,NaN,1.828707e+01,3.188088e-01,6.574103e-01,1.701200e+01,1.201094e+01,1.159542e+01,2.162251e-01,1.628685e+04,5.218212e+01,2.501039e+01,0.0,0.0,1.487489e+04,1.485026e+04,1.217327e+04,2.463522e+03,1.599540e+00,2.364954e+02,3.932706e+01,5.256369e+03,1.696658e-02,43.654138,1.0,1.163373e+05,18.958587,5.078174e-03,2.509239e+02,1.409376e+05,1.052330,2.806305,0.779048,1.751114,19.450903,3.598184e+04,71.487798,1.424365,3.013894,5541.061534,58.487335,3.261777e+04,1.089338,1.609580,2.317278,4.676423e+00,1.345909e+04,1.000375e+04,6.041064e+01,9.100055e-03,1.489924e+01,1.259326e+02,1.817518e+02,1.310995e+01,7.860697e+00,1.678481e+00,2.384164e+01,39.699756,6.728940e+00,35.822897,5.105248e-01,3.654693e+00,5.667057e+00,4.733504e+00,8.127810e+00,8.562271e+00,8.284432e+00,1.464519e+01,5.617042e+00,1.164563e+01,8.266068e-04,3.438509e-03,8.948493e-02,2.169717e+00,9.415082e+01,4.565374e+01,1.345679e-01,5.252973e-02,1.739382e+05,4.960634e+04,2.148961e+04,4.202174e+04,31457.505640,0.752463,1.674798,11.344703,57.623532,2.943059,12.815248,0.055038,0.085887,36.524017,3.0,148.153607,3.0,13.967923,414.084599,11029.03644,184.679439,5031.433284,47.654815,13.086344,5.157072e+02,1999-01-26 09:14:50.941333120,7126 days 14:45:09.058667136,1.951161e+01,6.046294e+00,2.135978e+00,2015-05-04 05:24:52.304973056,2.014877e+03,1.0,2017-02-13 02:48:02.923430400,650 days 21:23:10.618457584,650 days 21:23:10.618457584,6.508911e+02,5.175000e+01,4.177462e+01,1253 days 05:43:38.504816208,-1.938117e-02
min,NaN,NaN,5.000000e+02,5.000000e+02,0.000000e+00,5.310000e+00,4.930000e+00,0.000000e+00,NaN,-1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,0.0,0.0,1.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,-5.100000e-09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,1.0,1.100000e+04,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,0.640000,3.0,0.000000,1.920000,55.73000,0.010000,44.210000,0.200000,0.000000,7.000000e+00,1934-04-01 00:00:00,1096 days 00:00:00,3.000684e+00,1.000000e+00,0.000000e+00,2007-06-01 00:00:00,2.007000e+03,1.0,2008-01-01 00:00:00,61 days 00:00:00,61 days 00:00:00,6.100000e+01,0.000000e+00,3.600000e+01,1080 days 00:00:00,-1.000000e+00
25%,NaN,NaN,8.000000e+03,8.000000e+03,7.975000e+03,9.750000e+00,2.499500e+02,4.560000e+04,NaN,1.184000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.000000e+00,0.000000e+00,5.999000e+03,3.400000e+01,1.600000e+01,0.0,0.0,6.899750e+03,6.881140e+03,5.037000e+03,8.314400e+02,0.000000e+00,0.000000e+00,0.000000e+00,3.937900e+02,0.000000e+00,27.000000,1.0,8.000000e+04,13.430000,0.000000e+00,0.000000e+00,2.948400e+04,0.000000,1.000000,0.000000,1.000000,6.000000,9.782000e+03,59.000000,0.000000,1.000000,2202.000000,45.000000,1.400000e+04,0.000000,0.000000,1.000000,2.000000e+00,3.104000e+03,1.431000e+03,3.900000e+01,0.000000e+00,0.000000e+00,9.800000e+01,1.170000e+02,4.000000e+00,3.000000e+00,0.000000e+00,6.000000e+00,21.000000,2.000000e+00,17.000000,0.000000e+00,2.000000e+00,3.000000e+00,3.000000e+00,5.000000e+00,4.000000e+00,5.000000e+00,9.000000e+00,3.000000e+00,8.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,9.130000e+01,1.250000e+01,0.000000e+00,0.000000e+00,4.950000e+04,2.093500e+04,7.700000e+03,1.471300e+04,13998.750000,0.000000,0.000000,7.000000,38.600000,1.000000,7.000000,0.000000,0.000000,15.000000,3.0,53.725000,3.0,6.000000,147.780000,5104.92500,39.790000,2237.250000,45.000000,6.000000,2.340000e+02,1995-03-01 00:00:00,5205 days 00:00:00,1.425051e+01,3.000000e+00,1.200000e+00,2014-06-01 00:00:00,2.014000e+03,1.0,2016-04-01 00:00:00,335 days 00:00:00,335 days 00:00:00,3.350000e+02,3.400000e+01,3.600000e+01,1080 days 00:00:00,4.011407e-02
50%,NaN,NaN,1.200000e+04,1.200000e+04,1.200000e+04,1.274000e+01,3.754900e+02,6.500000e+04,NaN,1.765000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.100000e+01,0.000000e+00,1.118500e+04,5.260000e+01,2.300000e+01,0.0,0.0,1.217891e+04,1.215398e+04,1.000000e+04,1.630970e+03,0.000000e+00,0.000000e+00,0.000000e+00,1.922150e+03,0.000000e+00,44.000000,1.0,1.060000e+05,18.550000,0.000000e+00,0.000000e+00,8.016000e+04,1.000000,2.000000,1.000000,1.000000,12.000000,2.423300e+04,75.000000,1.000000,2.000000,4210.000000,60.000000,2.400000e+04,1.000000,0.000000,2.000000,4.000000e+00,7.402000e+03,4.600000e+03,6.380000e+01,0.000000e+00,0.000000e+00,1.290000e+02,1.640000e+02,8.000000e+00,5.000000e+00,1.000000e+00,1.300000e+01,38.000000,5.000000e+00,33.000000,0.000000e+00,3.000000e+00,5.000000e+00,4.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00,1.300000e+01,5.000000e+00,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,9.790000e+01,5.000000e+01,0.000000e+00,0.000000e+00,1.120490e+05,3.729200e+04,1.500000e+04,3.161400e+04,24670.000000,0.000000,1.000000,10.000000,59.800000,2.000000,11.000000,0.000000,0.000000,35.000000,3.0,110.650000,3.0,15.000000,307.650000,9346.01000,121.660000,4192.635000,45.000000,14.000000,4.800000e+02,2000-06-01 00:00:00,6635 days 00:00:00,1.816564e+01,6.021241e+00,2.000000e+00,2015-07-01 00:00:00,2.015000e+03,1.0,2017-06-01 00:00:00,609 days 00:00:00,609 days 00:00:00,6.090000e+02,5.200000e+01,3.600000e+01,1080 days 00:00:00,7.103566e-02
75%,NaN,NaN,2.000000e+04,2.000000e+04,2.000000e+04,1.599000e+01,5.802200e+02,9.000000e+04,NaN,2.406000e+01,0.000000e+00,1.000000e+00,3.100000e+01,0.000000e+00,1.400000e+01,0.000000e+00,1.979500e+04,7.100000e+01,3.200000e+01,0.0,0.0,2.064459e+04,2.061722e+04,1.712500e+04,3.093850e+03,0.000000e+00,0.000000e+00,0.000000e+00,7.998280e+03,0.000000e+00,61.000000,1.0,1.400000e+05,24.150000,0.000000e+00,0.000000e+00,2.103930e+05,2.000000,3.000000,1.000000,2.000000,22.000000,4.683300e+04,87.000000,2.000000,4.000000,7185.000000,73.000000,4.040000e+04,2.000000,2.000000,3.000000,6.000000e+00,1.868500e+04,1.212900e+04,8.510000e+01,0.000000e+00,0.000000e+00,1.520000e+02,2.300000e+02,1.600000e+01,1.000000e+01,3.000000e+00,2.800000e+01,58.000000,1.000000e+01,52.000000,0.000000e+00,5.000000e+00,7.000000e+00,6.000000e+00,1.100000e+01,1.100000e+01,1.000000e+01,1.900000e+01,7.000000e+00,1.400000e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00,1.000000e+02,7.500000e+01,0.000000e+00,0.000000e+00,2.515000e+05,6.243400e+04,2.790000e+04,5.646700e+04,40436.750000,1.000000,3.000000,15.000000,78.600000,4.000000,17.000000,0.000000,0.000000,56.000000,3.0,204.615000,3.0,23.000000,572.130000,15361.42000,267.570000,6886.502500,50.000000,18.000000,8.060000e+02,2004-05-01 00:00:00,8554 days 00:00:00,2.341958e+01,1.000000e+01,2.800000e+00,2016-05-01 00:00:00,2.016000e+03,1.0,2018-04-01 00:00:00,1004 days 00:00:00,1004 days 00:00:00,1.004000e+03,7.100000e+01,3.600000e+01,1080 days 00:00:00,1.060210e-01
max,NaN,NaN,4.000000e+04,4.000000e+04,4.000000e+04,3.099000e+01,1.719830e+03,1.099920e+07,NaN,9.990000e+02,3.900000e+01,8.000000e+00,2.260000e+02,1.290000e+02,9.000000e+01,8.600000e+01,2.904836e+06,8.923000e+02,1.760000e+02,0.0,0.0,6.329688e+04,6.329688e+04,4.000000e+04,2.819250e+04,1.188830e+03,3.985955e+04,7.174719e+03,4.219205e+04,2.000000e+01,226.000000,1.0,1.350000e+06,69.490000,1.400000e+01,9.152545e+06,8.000078e+06,18.000000,57.000000,25.000000,51.000000,511.000000,1.711009e+06,558.000000,28.000000,53.000000,776843.000000,198.000000,9.999999e+06,48.000000,79.000000,67.000000,6.400000e+01,9.580840e+05,5.599120e+05,3.182000e+02,1.000000e+01,2.499250e+05,9.990000e+02,8.520000e+02,4.380000e+02,3.140000e+02,5.100000e+01,6.390000e+02,202.000000,2.500000e+01,202.000000,5.100000e+01,3.500000e+01,6.300000e+01,6.300000e+01,7.000000e+01,1.590000e+02,8.300000e+01,1.270000e+02,4.500000e+01,9.000000e+01,6.000000e+00,4.000000e+00,3.900000e+01,3.200000e+01,1.000000e+02,1.000000e+02,1.200000e+01,8.500000e+01,9.999999e+06,3.408095e+06,1.105500e+06,2.101913e+06,357135.000000,6.000000,17.000000,82.000000,212.600000,38.000000,92.000000,20.000000,16.000000,132.000000,3.0,943.940000,3.0,37.000000,2343.150000,39542.45000,1407.860000,33601.000000,521.350000,181.000000,9.990000e+02,2015-08-01 00:00:00,30803 days 00:00:00,8.433402e+01,1.000000e+01,6.800000e+00,2018-12-01 00:00:00,2.018000e+03,1.0,2019-02-01 00:00:00,2130 days 00:00:00,2130 days 00:00:00,2.130000e+03,8.920000e+02,6.000000e+01,1800 days 00:00:00,9.966068e-01
std,NaN,NaN,8.667391e+03,8.663248e+03,8.665941e+03,4.728371e+00,2.601341e+02,6.928921e+04,NaN,1.078072e+01,8.791842e-01,9.404292e-01,2.307284e+01,2.869929e+01,5.455698e+00,6.056960e-01,2.231298e+04,2.439404e+01,1.197061e+01,0.0,0.0,1.033147e+04,1.032993e+04,8.813647e+03,2.598201e+03,1.071379e+01,9.384635e+02,1.649677e+02,6.919569e+03,1.465757e-01,21.369333,0.0,5.715472e+04,7.653980,7.764679e-02,1.143293e+04,1.571815e+05,1.206996,2.991646,0.991109,1.682732,24.700549,4.283004e+04,22.831954,1.572889,2.697505,5482.391482,20.770167,3.669975e+04,1.580463,2.820594,2.541422,3.167942e+00,1.622314e+04,1.511847e+04,2.810351e+01,1.099544e-01,8.165580e+02,5.216104e+01,9.438579e+01,1.630881e+01,8.711410e+00,2.007262e+00,3.064920e+01,22.709590,5.851759e+00,22.438611,1.323216e+00,2.243809e+00,3.296352e+00,2.940677e+00,4.799175e+00,7.371852e+00,4.541826e+00,8.106411e+00,3.211084e+00,5.465180e+00,3.067410e-02,6.266762e-02,5.051212e-01,1.832810e+00,8.738294e+00,3.594585e+01,3.785539e-01,4.018550e-01,1.776286e+05,4.758263e+04,2.139678e+04,4.312056e+04,26573.976972,1.091157,1.831506,6.505817,26.181920,3.213186,8.336620,0.462616,0.424309,23.905672,0.0,129.029635,0.0,9.765405,360.416982,7467.23572,195.447292,3666.297994,7.303985,8.269720,3.126673e+02,NaN,2772 days 01:47:36.067963840,7.589527e+00,3.455342e+00,1.287624e+00,NaN,1.614219e+00,0.0,NaN,371 days 22:25:01.037326044,371 days 22:25:01.037326044,3.719340e+02,2.438697e+01,1.025889e+01,307 days 18:23:52.760583708,2.744446e-01

In [102]:
loan.columns=='revol_util_perc'

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False])

In [103]:
loan.head(30)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,zip_code_prefix,earliest_cr_line_date,credit_history,credit_history_years,emp_length_years,credit_score,issue_date,issue_date_year,issue_date_days,last_pymnt_date,loan_length,loan_length_term,loan_length_days,revol_util_perc,term_months,term_days,apy
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,Chef,10+ years,RENT,55000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,109xx,NY,18.24,0.0,Apr-2001,1.0,0.0,45.0,9.0,1.0,4341,10.3,34.0,w,2386.02,2386.02,167.02,167.02,113.98,53.04,0.0,0.0,0.0,Feb-2019,84.92,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,16901.0,2.0,2.0,1.0,2.0,2.0,12560.0,69.0,2.0,7.0,2137.0,28.0,42000.0,1.0,11.0,2.0,9.0,1878.0,34360.0,5.9,0.0,0.0,140.0,212.0,1.0,1.0,0.0,1.0,NaN,2.0,NaN,0.0,2.0,5.0,3.0,3.0,16.0,7.0,18.0,5.0,9.0,0.0,0.0,0.0,3.0,100.0,0.0,1.0,0.0,60124.0,16901.0,36500.0,18124.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,109.0,2001-04-01,6331 days,17.333333,10.000000,2.0,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,10.000000,36,1080 days,-1.0
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,Postmaster,10+ years,MORTGAGE,90000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,713xx,LA,26.52,0.0,Jun-1987,0.0,71.0,75.0,13.0,1.0,12315,24.2,44.0,w,29387.75,29387.75,1507.11,1507.11,612.25,894.86,0.0,0.0,0.0,Feb-2019,777.23,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,1208.0,321915.0,4.0,4.0,2.0,3.0,3.0,87153.0,88.0,4.0,5.0,998.0,57.0,50800.0,2.0,15.0,2.0,10.0,24763.0,13761.0,8.3,0.0,0.0,163.0,378.0,4.0,3.0,3.0,4.0,NaN,4.0,NaN,0.0,2.0,4.0,4.0,9.0,27.0,8.0,14.0,4.0,13.0,0.0,0.0,0.0,6.0,95.0,0.0,1.0,0.0,372872.0,99468.0,15000.0,94072.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,713.0,1987-06-01,11384 days,31.167693,10.000000,3.2,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,24.000000,60,1800 days,-1.0
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,490xx,MI,10.51,0.0,Apr-2011,0.0,0.0,0.0,8.0,0.0,4599,19.1,13.0,w,4787.21,4787.21,353.89,353.89,212.79,141.10,0.0,0.0,0.0,Feb-2019,180.69,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,110299.0,0.0,1.0,0.0,2.0,14.0,7150.0,72.0,0.0,2.0,0.0,35.0,24100.0,1.0,5.0,0.0,4.0,18383.0,13800.0,0.0,0.0,0.0,87.0,92.0,15.0,14.0,2.0,77.0,NaN,14.0,NaN,0.0,0.0,3.0,3.0,3.0,4.0,6.0,7.0,3.0,8.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,136927.0,11749.0,13800.0,10000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,490.0,2011-04-01,2679 days,7.334702,6.000000,3.0,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,19.000000,36,1080 days,-1.0
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,IT Supervisor,10+ years,MORTGAGE,92000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,985xx,WA,16.74,0.0,Feb-2006,0.0,0.0,0.0,10.0,0.0,5468,78.1,13.0,w,3831.93,3831.93,286.71,286.71,168.07,118.64,0.0,0.0,0.0,Feb-2019,146.51,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,686.0,305049.0,1.0,5.0,3.0,5.0,5.0,30683.0,68.0,0.0,0.0,3761.0,70.0,7000.0,2.0,4.0,3.0,5.0,30505.0,1239.0,75.2,0.0,0.0,62.0,154.0,64.0,5.0,3.0,64.0,NaN,5.0,NaN,0.0,1.0,2.0,1.0,2.0,7.0,2.0,3.0,2.0,10.0,0.0,0.0,0.0,3.0,100.0,100.0,0.0,0.0,385183.0,36151.0,5000.0,44984.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,985.0,2006-02-01,4564 days,12.495551,10.000000,3.2,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,78.000000,36,1080 days,-1.0
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,Mechanic,10+ years,MORTGAGE,57250.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,212xx,MD,26.35,0.0,Dec-2000,0.0,0.0,0.0,12.0,0.0,829,3.6,26.0,w,29339.02,29339.02,1423.21,1423.21,660.98,762.23,0.0,0.0,0.0,Feb-2019,731.78,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,116007.0,3.0,5.0,3.0,5.0,4.0,28845.0,89.0,2.0,4.0,516.0,54.0,23100.0,1.0,0.0,0.0,9.0,9667.0,8471.0,8.9,0.0,0.0,53.0,216.0,2.0,2.0,2.0,2.0,NaN,13.0,NaN,0.0,2.0,2.0,3.0,8.0,9.0,6.0,15.0,2.0,12.0,0.0,0.0,0.0,5.0,92.3,0.0,0.0,0.0,157548.0,29674.0,9300.0,32332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,212.0,2000-12-01,6452 days,17.664613,10.000000,2.6,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,3.000000,60,1800 days,-1.0
5,NaN,NaN,5550,5550,5550.0,36 months,15.02,192.45,C,C3,Director COE,10+ years,MORTGAGE,152500.0,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,461xx,IN,37.94,0.0,Sep-2002,3.0,0.0,0.0,18.0,0.0,53854,48.1,44.0,w,5302.50,5302.50,377.95,377.95,247.50,130.45,0.0,0.0,0.0,Feb-2019,192.45,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,685749.0,1.0,7.0,2.0,3.0,4.0,131524.0,72.0,1.0,4.0,17584.0,58.0,111900.0,2.0,4.0,6.0,8.0,40338.0,23746.0,64.0,0.0,0.0,195.0,176.0,10.0,4.0,6.0,20.0,NaN,3.0,NaN,0.0,4.0,6.0,6.0,10.0,23.0,9.0,15.0,7.0,18.0,0.0,0.0,0.0,4.0,100.0,60.0,0.0,0.0,831687.0,185378.0,65900.0,203159.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,461.0,2002-09-01,5813 days,15.915127,10.000000,2.4,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,48.000000,36,1080 days,-1.0
6,NaN,NaN,2000,2000,2000.0,36 months,17.97,72.28,D,D1,Account Manager,4 years,RENT,51000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,606xx,IL,2.40,0.0,Nov-2004,1.0,0.0,0.0,1.0,0.0,0,NaN,9.0,w,1914.71,1914.71,141.56,141.56,85.29,56.27,0.0,0.0,0.0,Feb-2019,72.28,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,854.0,0.0,0.0,2.0,3.0,7.0,0.0,NaN,0.0,1.0,0.0,100.0,0.0,0.0,0.0,1.0,4.0,854.0,NaN,NaN,0.0,0.0,169.0,40.0,23.0,7.0,0.0,NaN,NaN,1.0,NaN,0.0,0.0,0.0,0.0,3.0,5.0,0.0,3.0,0.0,1.0,0.0,0.0,0.0,2.0,100.0,NaN,0.0,0.0,854.0,854.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,606.0,2004-11-01,5021 days,13.746749,4.000000,3.0,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,49.907401,36,1080 days,-1.0
7,NaN,NaN,6000,6000,6000.0,36 months,13.56,203.79,C,C1,Assistant Director,10+ years,RENT,65000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,460xx,IN,30.10,0.0,Nov-1997,0.0,0.0,0.0,19.0,0.0,38476,69.3,37.0,w,5864.01,5864.01,201.53,201.53,135.99,65.54,0.0,0.0,0.0,Feb-2019,208.31,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,91535.0,0.0,5.0,0.0,1.0,23.0,53059.0,87.0,0.0,2.0,9413.0,74.0,55500.0,1.0,2.0,0.0,3.0,5085.0,3034.0,90.8,0.0,0.0,169.0,253.0,13.0,13.0,1.0,14.0,NaN,13.0,NaN,0.0,7.0,12.0,8.0,10.0,15.0,14.0,20.0,12.0,19.0,0.0,0.0,0.0,0.0,100.0,85.7,0.0,0.0,117242.0,91535.0,33100.0,61742.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DirectPay,N,NaN,NaN,NaN,NaN,NaN,NaN,460.0,1997-11-01,7578 days,20.747433,10.000000,2.0,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,69.000000,36,1080 days,-1.0
8,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Legal Assistant III,10+ years,MORTGAGE,53580.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,327xx,FL,21.16,0.0,Aug-1998,1.0,32.0,0.0,8.0,0.0,8018,35.2,38.0,w,4786.79,4786.79,353.89,353.89,213.21,140.68,0.0,0.0,0.0,Feb-2019,180.69,Mar-2019,Feb-2019,0.0,45.0,1,Individual,NaN,NaN,NaN,0.0,0.0,41882.0,5.0,2.0,5.0,5.0,3.0,33864.0,98.0,1.0,6.0,3132.0,73.0,22800.0,2.0,1.0,4.0,12.0,5235.0,13786.0,35.9,0.0,0.0,145.0,244.0,6.0,3.0,3.0,6.0,33.0,2.0,32.0,2.0,4.0,5.0,5.0,10.0,20.0,6.0,15.0,5.0,8.0,0.0,0.0,0.0,6.0,78.9,60.0,0.0,0.0,57426.0,41882.0,21500.0,34626.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,327.0,1998-08-01,7305 days,20.000000,10.000000,3.0,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,35.000000,36,1080 days,-1.0
9,NaN,NaN,6000,6000,6000.0,36 months,14.47,206.44,C,C2,NaN,< 1 year,OWN,300000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,068xx,CT,17.43,1.0,Apr-2002,1.0,17.0,0.0,38.0,0.0,65950,49.8,58.0,w,5730.20,5730.20,405.64,405.64,269.80,135.84,0.0,0.0,0.0,Feb-2019,206.44,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,349502.0,1.0,4.0,1.0,3.0,7.0,39961.0,45.0,1.0,12.0,15926.0,48.0,132500.0,2.0,2.0,2.0,15.0,9197.0,38683.0,60.6,0.0,0.0,166.0,200.0,4.0,4.0,1.0,4.0,NaN,4.0,17.0,0.0,16.0,20.0,19.0,26.0,9.0,33.0,48.0,20.0,38.0,0.0,0.0,0.0,2.0,100.0,26.3,0.0,0.0,477390.0,105911.0,98300.0,89600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,68.0,2002-04-01,5966 days,16.334018,1.000000,2.2,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,49.000000,36,1080 days,-1.0
10,NaN,NaN,5500,5500,5500.0,36 months,22.35,211.05,D,D5,NaN,< 1 year,MORTGAGE,50000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,711xx,LA,15.94,1.0,May-2007,0.0,22.0,0.0,6.0,0.0,4529,94.4,13.0,w,5280.75,5280.75,411.86,411.86,219.25,192.61,0.0,0.0,0.0,Feb-2019,211.05,Mar-2019,Feb-2019,0.0,22.0,1,Individual,NaN,NaN,NaN,0.0,0.0,228151.0,2.0,2.0,1.0,2.0,4.0,13656.0,87.0,1.0,1.0,2837.0,89.0,4800.0,2.0,0.0,0.0,3.0,38025.0,271.0,94.4,0.0,0.0,139.0,105.0,5.0,4.0,3.0,5.0,22.0,4.0,22.0,2.0,3.0,3.0,3.0,4.0,5.0,3.0,5.0,3.0,6.0,0.0,0.0,1.0,2.0,84.6,100.0,0.0,0.0,243452.0,18185.0,4800.0,15649.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,711.0,2007-05-01,4110 days,11.252567,1.000000,3.8,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,94.000000,36,1080 days,-1.0
11,NaN,NaN,28000,28000,28000.0,60 months,11.31,613.13,B,B3,Consultant,2 years,MORTGAGE,70000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,300xx,GA,22.01,0.0,Dec-2003,1.0,0.0,0.0,10.0,0.0,56152,55.9,23.0,w,27298.25,27298.25,1199.87,1199.87,701.75,498.12,0.0,0.0,0.0,Feb-2019,613.13,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,177406.0,1.0,1.0,0.0,0.0,62.0,9484.0,54.0,1.0,2.0,16284.0,56.0,100400.0,1.0,0.0,1.0,2.0,17741.0,44248.0,55.9,0.0,0.0,180.0,165.0,6.0,6.0,1.0,6.0,NaN,6.0,NaN,0.0,5.0,5.0,8.0,9.0,13.0,8.0,9.0,5.0,10.0,0.0,0.0,0.0,1.0,100.0,37.5,0.0,0.0,259435.0,65636.0,100400.0,17535.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DirectPay,N,NaN,NaN,NaN,NaN,NaN,NaN,300.0,2003-12-01,5357 days,14.666667,2.000000,1.4,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,55.000000,60,1800 days,-1.0
12,NaN,NaN,11200,11200,11200.0,36 months,8.19,351.95,A,A4,Job Coach Supervisor,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,840xx,UT,23.60,0.0,Jun-2003,0.0,0.0,0.0,20.0,0.0,8836,16.6,27.0,w,10647.10,10647.10,696.26,696.26,552.90,143.36,0.0,0.0,0.0,Feb-2019,351.95,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,249643.0,2.0,8.0,2.0,3.0,1.0,69959.0,68.0,0.0,0.0,4603.0,45.0,53100.0,3.0,0.0,3.0,3.0,12482.0,26289.0,24.7,0.0,0.0,170.0,186.0,25.0,1.0,4.0,65.0,NaN,1.0,NaN,0.0,4.0,5.0,5.0,5.0,13.0,10.0,10.0,5.0,20.0,0.0,0.0,0.0,2.0,100.0,20.0,0.0,0.0,345654.0,78795.0,34900.0,114578.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,840.0,2003-06-01,5540 days,15.167693,10.000000,0.6,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,16.000000,36,1080 days,-1.0
13,NaN,NaN,6500,6500,6500.0,36 months,17.97,234.90,D,D1,Quality Field Engineer,4 years,MORTGAGE,154000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,278xx,NC,28.78,2.0,Oct-2008,0.0,6.0,0.0,27.0,0.0,23754,60.4,41.0,w,6222.82,6222.82,460.07,460.07,277.18,182.89,0.0,0.0,0.0,Feb-2019,234.90,Mar-2019,Feb-2019,0.0,6.0,1,Individual,NaN,NaN,NaN,0.0,0.0,116747.0,2.0,8.0,3.0,5.0,1.0,92993.0,78.0,1.0,6.0,3943.0,72.0,39300.0,3.0,3.0,3.0,11.0,4324.0,4578.0,62.8,1.0,0.0,122.0,74.0,11.0,1.0,0.0,13.0,NaN,4.0,NaN,1.0,5.0,19.0,5.0,8.0,17.0,19.0,24.0,19.0,27.0,0.0,0.0,1.0,4.0,90.2,20.0,0.0,0.0,169160.0,116747.0,12300.0,129860.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,278.0,2008-10-01,3591 days,9.831622,4.000000,3.0,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,60.000000,36,1080 days,-1.0
14,NaN,NaN,22000,22000,22000.0,60 months,12.98,500.35,B,B5,Teller,10+ years,MORTGAGE,65000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,413xx,KY,11.19,0.0,Jul-1990,0.0,0.0,0.0,8.0,0.0,134,0.5,16.0,w,21472.40,21472.40,976.90,976.90,527.60,449.30,0.0,0.0,0.0,Feb-2019,500.35,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,22337.0,1.0,1.0,0.0,0.0,36.0,22127.0,NaN,1.0,2.0,3.0,1.0,29500.0,0.0,0.0,0.0,2.0,3191.0,27197.0,0.0,0.0,0.0,162.0,341.0,4.0,4.0,1.0,4.0,NaN,15.0,NaN,0.0,1.0,2.0,3.0,4.0,6.0,6.0,8.0,2.0,8.0,0.0,0.0,0.0,1.0,100.0,0.0,0.0,0.0,71932.0,22337.0,27200.0,38535.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,413.0,1990-07-01,10258 days,28.084873,10.000000,1.8,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,0.000000,60,1800 days,-1.0
15,NaN,NaN,3500,3500,3500.0,36 months,16.14,123.30,C,C4,respritory therapist,10+ years,MORTGAGE,80000.0,Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,604xx,IL,13.63,0.0,Dec-1988,0.0,43.0,0.0,7.0,0.0,8952,58.5,27.0,w,3346.52,3346.52,218.36,218.36,153.48,64.88,0.0,0.0,0.0,Feb-2019,123.30,Mar-2019,Feb-2019,0.0,48.0,1,Joint App,104424.0,10.77,Verified,0.0,0.0,16085.0,2.0,2.0,0.0,0.0,57.0,7133.0,26.0,3.0,4.0,3873.0,38.0,15300.0,0.0,0.0,1.0,4.0,2298.0,4127.0,48.4,0.0,0.0,144.0,360.0,4.0,4.0,2.0,7.0,NaN,7.0,117.0,7.0,1.0,3.0,2.0,3.0,10.0,5.0,15.0,3.0,7.0,0.0,0.0,0.0,3.0,76.0,50.0,0.0,0.0,42328.0,16085.0,8000.0,27028.0,10286.0,May-2002,2.0,3.0,2.0,44.1,0.0,6.0,0.0,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,604.0,1988-12-01,10835 days,29.664613,10.000000,2.6,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,58.000000,36,1080 days,-1.0
16,NaN,NaN,7000,7000,7000.0,36 months,12.98,235.80,B,B5,Worship Director,4 years,MORTGAGE,102500.0,Not Verified,Dec-2018,Current,n,NaN,NaN,house,Home buying,436xx,OH,15.20,0.0,Dec-2002,0.0,38.0,0.0,9.0,0.0,1057,7.2,21.0,w,6678.10,6678.10,464.03,464.03,321.90,142.13,0.0,0.0,0.0,Feb-2019,235.80,Mar-2019,Feb-2019,0.0,68.0,1,Individual,NaN,NaN,NaN,0.0,0.0,174891.0,1.0,4.0,1.0,1.0,10.0,75652.0,78.0,1.0,2.0,0.0,69.0,14700.0,1.0,0.0,3.0,3.0,19432.0,7200.0,0.0,0.0,0.0,182.0,192.0,6.0,6.0,4.0,26.0,NaN,10.0,NaN,1.0,0.0,2.0,2.0,3.0,8.0,4.0,9.0,2.0,9.0,0.0,0.0,0.0,2.0,80.0,0.0,0.0,0.0,214624.0,76709.0,7200.0,96826.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,436.0,2002-12-01,5722 days,15.665982,4.000000,1.8,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,7.000000,36,1080 days,-1.0
17,NaN,NaN,25000,25000,25000.0,60 months,16.91,620.11,C,C5,Processor,10+ years,MORTGAGE,23878.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,453xx,OH,6.26,0.0,Oct-2010,0.0,0.0,0.0,4.0,0.0,3044,54.4,8.0,w,24460.59,24460.59,1204.99,1204.99,539.41,665.58,0.0,0.0,0.0,Feb-2019,620.11,Mar-2019,Feb-2019,0.0,NaN,1,Joint App,64793.0,18.91,Not Verified,0.0,0.0,79660.0,0.0,0.0,0.0,0.0,47.0,0.0,NaN,0.0,0.0,1044.0,54.0,5600.0,0.0,0.0,0.0,0.0,19915.0,0.0,104.4,0.0,0.0,90.0,98.0,27.0,27.0,2.0,84.0,NaN,NaN,NaN,0.0,1.0,3.0,1.0,1.0,2.0,3.0,4.0,3.0,4.0,0.0,0.0,0.0,0.0,100.0,100.0,0.0,0.0,92334.0,3044.0,1000.0,0.0,24654.0,Aug-2003,0.0,2.0,9.0,78.9,1.0,12.0,0.0,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,453.0,2010-10-01,2861 days,7.832991,10.000000,2.8,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,54.000000,60,1800 days,-1.0
18,NaN,NaN,16000,16000,16000.0,60 months,20.89,431.87,D,D4,Neonatal Nurse Practitioner,4 years,MORTGAGE,120000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,720xx,AR,27.57,1.0,Jul-2005,0.0,8.0,0.0,13.0,0.0,18826,82.2,37.0,w,15690.66,15690.66,835.89,835.89,309.34,526.55,0.0,0.0,0.0,Feb-2019,431.87,Mar-2019,Feb-2019,0.0,35.0,1,Individual,NaN,NaN,NaN,0.0,0.0,434239.0,1.0,6.0,1.0,4.0,4.0,247928.0,90.0,1.0,1.0,9439.0,87.0,22900.0,6.0,1.0,2.0,5.0,33403.0,430.0,96.8,0.0,0.0,136.0,146.0,12.0,4.0,2.0,12.0,48.0,4.0,8.0,2.0,2.0,4.0,2.0,5.0,24.0,6.0,10.0,4.0,13.0,0.0,0.0,0.0,2.0,86.5,100.0,0.0,0.0,444217.0,266754.0,13500.0,239338.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,720.0,2005-07-01,4779 days,13.084189,4.000000,3.6,2018-12-01,2018,1,2019-02-01,62 days,62 days,62.0,82.000000,60,1800 days,-1.0

In [104]:
loan.isna().sum()

id                  2260668
member_id           2260668
loan_amnt                 0
funded_amnt               0
funded_amnt_inv           0
                     ...
loan_length_days          0
revol_util_perc           0
term_months               0
term_days                 0
apy                       0
Length: 162, dtype: int64

# Subset Public Data
We are only concerned with loans that are complete. Either they are paid off or charged off. Loans that are still ongoing are also interesting to look at, but they require their own separate analysis. Because our time is limited, we can only do one set and complete loans seems the most promising.

In addition, there are a number of loans that have a small length. That is they were taken out and repaid quickly. I'm not sure why that is, but such loans make little difference. If an investor makes a loan and it is repaid in a few days, they he neither makes money nor loses money and must make a new loan. So for now, we ignore them.

In [ ]:
loan.verification_status.unique()

In [119]:
public_columns = [
'loan_amnt',
'term_months',
'int_rate',
'credit_score',
'emp_length_years',
'home_ownership',
'annual_inc',
'issue_date',
'verification_status',
'dti',
'delinq_2yrs',
'credit_history_years',
'inq_last_6mths',
'mths_since_last_delinq',
'mths_since_last_record',
'open_acc',
'pub_rec',
'revol_bal',
'revol_util_perc',
'total_acc']

In [120]:
public_data = complete[public_columns]

In [122]:
public_data.isna().sum()

loan_amnt                 0
term_months               0
int_rate                  0
credit_score              0
emp_length_years          0
home_ownership            0
annual_inc                0
issue_date                0
verification_status       0
dti                       0
delinq_2yrs               0
credit_history_years      0
inq_last_6mths            0
mths_since_last_delinq    0
mths_since_last_record    0
open_acc                  0
pub_rec                   0
revol_bal                 0
revol_util_perc           0
total_acc                 0
dtype: int64

In [123]:
public_data.head()

,loan_amnt,term_months,int_rate,credit_score,emp_length_years,home_ownership,annual_inc,issue_date,verification_status,dti,delinq_2yrs,credit_history_years,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util_perc,total_acc
152,40000,60,16.14,2.6,1.0,MORTGAGE,45000.0,2018-12-01,Verified,50.53,0.0,9.166324,0.0,0.0,0.0,18.0,0.0,34971,64.0,37.0
170,20000,36,7.56,0.4,10.0,MORTGAGE,100000.0,2018-12-01,Not Verified,18.92,0.0,19.496235,0.0,48.0,0.0,9.0,0.0,25416,29.0,19.0
186,4500,36,11.31,1.4,10.0,RENT,38500.0,2018-12-01,Not Verified,4.64,0.0,14.666667,0.0,25.0,0.0,12.0,0.0,4472,15.0,25.0
215,8425,36,27.27,4.8,3.0,MORTGAGE,450000.0,2018-12-01,Verified,12.37,0.0,20.832307,0.0,0.0,0.0,21.0,0.0,36812,65.0,37.0
369,4000,36,17.97,3.0,5.0,MORTGAGE,60000.0,2018-12-01,Source Verified,19.10,0.0,11.167693,1.0,38.0,0.0,11.0,0.0,382,7.0,18.0

In [128]:
public_data_y = complete.apy

In [129]:
public_data_y

152        0.132965
170        0.065264
186        0.066180
215        0.237352
369        0.075797
             ...
2260654   -0.909940
2260655   -0.764965
2260656    0.344607
2260658    0.188903
2260664    0.255274
Name: apy, Length: 1261477, dtype: float64

In [130]:
public_data_y.describe()

count    1.261477e+06
mean    -1.938117e-02
std      2.744446e-01
min     -1.000000e+00
25%      4.011407e-02
50%      7.103566e-02
75%      1.060210e-01
max      9.966068e-01
Name: apy, dtype: float64

In [131]:
categorical = ['verification_status','home_ownership']

In [138]:
public_data_dummy = pd.get_dummies(public_data[categorical],dummy_na=0,dtype=int,drop_first=True)
public_data_cat = pd.concat([public_data, public_data_dummy], axis=1)

In [139]:
public_data_cat.head()

,loan_amnt,term_months,int_rate,credit_score,emp_length_years,home_ownership,annual_inc,issue_date,verification_status,dti,delinq_2yrs,credit_history_years,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util_perc,total_acc,verification_status_Source Verified,verification_status_Verified,home_ownership_MORTGAGE,home_ownership_NONE,home_ownership_OTHER,home_ownership_OWN,home_ownership_RENT
152,40000,60,16.14,2.6,1.0,MORTGAGE,45000.0,2018-12-01,Verified,50.53,0.0,9.166324,0.0,0.0,0.0,18.0,0.0,34971,64.0,37.0,0,1,1,0,0,0,0
170,20000,36,7.56,0.4,10.0,MORTGAGE,100000.0,2018-12-01,Not Verified,18.92,0.0,19.496235,0.0,48.0,0.0,9.0,0.0,25416,29.0,19.0,0,0,1,0,0,0,0
186,4500,36,11.31,1.4,10.0,RENT,38500.0,2018-12-01,Not Verified,4.64,0.0,14.666667,0.0,25.0,0.0,12.0,0.0,4472,15.0,25.0,0,0,0,0,0,0,1
215,8425,36,27.27,4.8,3.0,MORTGAGE,450000.0,2018-12-01,Verified,12.37,0.0,20.832307,0.0,0.0,0.0,21.0,0.0,36812,65.0,37.0,0,1,1,0,0,0,0
369,4000,36,17.97,3.0,5.0,MORTGAGE,60000.0,2018-12-01,Source Verified,19.10,0.0,11.167693,1.0,38.0,0.0,11.0,0.0,382,7.0,18.0,1,0,1,0,0,0,0

In [140]:
public_data_cat = public_data_cat.drop(categorical, axis=1)

In [147]:
public_data_cat

,loan_amnt,term_months,int_rate,credit_score,emp_length_years,annual_inc,issue_date,dti,delinq_2yrs,credit_history_years,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util_perc,total_acc,verification_status_Source Verified,verification_status_Verified,home_ownership_MORTGAGE,home_ownership_NONE,home_ownership_OTHER,home_ownership_OWN,home_ownership_RENT
152,40000,60,16.14,2.6,1.0,45000.0,2018-12-01,50.53,0.0,9.166324,0.0,0.0,0.0,18.0,0.0,34971,64.0,37.0,0,1,1,0,0,0,0
170,20000,36,7.56,0.4,10.0,100000.0,2018-12-01,18.92,0.0,19.496235,0.0,48.0,0.0,9.0,0.0,25416,29.0,19.0,0,0,1,0,0,0,0
186,4500,36,11.31,1.4,10.0,38500.0,2018-12-01,4.64,0.0,14.666667,0.0,25.0,0.0,12.0,0.0,4472,15.0,25.0,0,0,0,0,0,0,1
215,8425,36,27.27,4.8,3.0,450000.0,2018-12-01,12.37,0.0,20.832307,0.0,0.0,0.0,21.0,0.0,36812,65.0,37.0,0,1,1,0,0,0,0
369,4000,36,17.97,3.0,5.0,60000.0,2018-12-01,19.10,0.0,11.167693,1.0,38.0,0.0,11.0,0.0,382,7.0,18.0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260654,30000,60,17.09,3.0,2.0,80000.0,2017-10-01,23.22,0.0,16.665298,1.0,46.0,0.0,21.0,0.0,19224,30.0,69.0,0,0,0,0,0,0,1
2260655,18000,60,30.65,5.6,10.0,77000.0,2017-10-01,8.08,0.0,13.913758,1.0,38.0,0.0,9.0,0.0,10100,45.0,15.0,0,1,1,0,0,0,0
2260656,17950,60,30.17,5.4,10.0,53758.0,2017-10-01,33.24,0.0,17.664613,1.0,0.0,80.0,11.0,1.0,5959,35.0,24.0,1,0,1,0,0,0,0
2260658,15000,60,16.02,2.8,1.0,85000.0,2017-10-01,14.66,0.0,17.418207,3.0,36.0,0.0,19.0,0.0,6988,24.0,87.0,0,1,0,0,0,0,1
2260664,12000,60,25.82,4.6,1.0,30000.0,2017-10-01,19.28,3.0,15.419576,1.0,13.0,0.0,10.0,0.0,3497,20.0,26.0,0,0,1,0,0,0,0

In [148]:
public_data_cat.to_csv("analysis-predictors.csv")
public_data_y.to_csv("analysis-target.csv")
complete.to_csv("complete.csv")

In [153]:
public_data_cat.to_pickle("analysis-predictors.bz2")
public_data_y.to_pickle("analysis-target.bz2")
complete.to_pickle("complete.bz2")

In [152]:
df.shape

(1261477, 162)

In [25]:
# Load the compressed pickle file
loan_complete_df = pd.read_pickle("analysis-predictors.bz2", compression='bz2')
print(loan_complete_df.head())

     loan_amnt  term_months  int_rate  credit_score  emp_length_years  \
152      40000           60     16.14           2.6               1.0
170      20000           36      7.56           0.4              10.0
186       4500           36     11.31           1.4              10.0
215       8425           36     27.27           4.8               3.0
369       4000           36     17.97           3.0               5.0

     annual_inc issue_date    dti  delinq_2yrs  credit_history_years  \
152     45000.0 2018-12-01  50.53          0.0              9.166324
170    100000.0 2018-12-01  18.92          0.0             19.496235
186     38500.0 2018-12-01   4.64          0.0             14.666667
215    450000.0 2018-12-01  12.37          0.0             20.832307
369     60000.0 2018-12-01  19.10          0.0             11.167693

     inq_last_6mths  mths_since_last_delinq  mths_since_last_record  open_acc  \
152             0.0                     0.0                     0.0      18.0
170             0.0                    48.0                     0.0       9.0
186             0.0                    25.0                     0.0      12.0
215             0.0                     0.0                     0.0      21.0
369             1.0                    38.0                     0.0      11.0

     pub_rec  revol_bal  revol_util_perc  total_acc  \
152      0.0      34971             64.0       37.0
170      0.0      25416             29.0       19.0
186      0.0       4472             15.0       25.0
215      0.0      36812             65.0       37.0
369      0.0        382              7.0       18.0

     verification_status_Source Verified  verification_status_Verified  \
152                                    0                             1
170                                    0                             0
186                                    0                             0
215                                    0                             1
369                                    1                             0

     home_ownership_MORTGAGE  home_ownership_NONE  home_ownership_OTHER  \
152                        1                    0                     0
170                        1                    0                     0
186                        0                    0                     0
215                        1                    0                     0
369                        1                    0                     0

     home_ownership_OWN  home_ownership_RENT
152                   0                    0
170                   0                    0
186                   0                    1
215                   0                    0
369                   0                    0